// O NOME EM PORTUGUÊS de cada ícone dos Destaques, para o seletor do editor
// (decisão do operador, 03/10/2026; todos os ícones do Lucide desde 05/10/2026).
// Fica aqui, e não no dicionário, porque o admin é em português, com o texto na
// própria tela (decisão de 23/09). O valor gravado no curso continua sendo o
// nome técnico (a chave), que o site do aluno lê. Os 55 de sempre mantêm o nome
// de 03/10. Ícone do Lucide sem nome aqui reprova um teste — inclusive depois
// de atualizar o lucide-react, que às vezes acrescenta ou renomeia ícones.
// Este arquivo só entra pelo seletor (lazy): o aluno não o baixa.
export const NOME_DO_ICONE: Record<string, string> = {
  "a-arrow-down": "Letra A com seta para baixo",
  "a-arrow-up": "Letra A com seta para cima",
  "a-large-small": "Tamanho da letra",
  "accessibility": "Acessibilidade",
  "activity": "Atividade",
  "air-vent": "Saída de ar",
  "airplay": "Espelhar tela",
  "alarm-clock": "Despertador",
  "alarm-clock-check": "Despertador com visto",
  "alarm-clock-minus": "Despertador com menos",
  "alarm-clock-off": "Despertador desligado",
  "alarm-clock-plus": "Despertador com mais",
  "alarm-smoke": "Detector de fumaça",
  "album": "Álbum",
  "align-center": "Texto centralizado",
  "align-center-horizontal": "Alinhar ao centro (horizontal)",
  "align-center-vertical": "Alinhar ao centro (vertical)",
  "align-end-horizontal": "Alinhar ao fim (horizontal)",
  "align-end-vertical": "Alinhar ao fim (vertical)",
  "align-horizontal-distribute-center": "Distribuir na horizontal pelo centro",
  "align-horizontal-distribute-end": "Distribuir na horizontal pelo fim",
  "align-horizontal-distribute-start": "Distribuir na horizontal pelo início",
  "align-horizontal-justify-center": "Justificar na horizontal ao centro",
  "align-horizontal-justify-end": "Justificar na horizontal ao fim",
  "align-horizontal-justify-start": "Justificar na horizontal ao início",
  "align-horizontal-space-around": "Espaçar em volta (horizontal)",
  "align-horizontal-space-between": "Espaçar entre (horizontal)",
  "align-justify": "Texto justificado",
  "align-left": "Texto à esquerda",
  "align-right": "Texto à direita",
  "align-start-horizontal": "Alinhar ao início (horizontal)",
  "align-start-vertical": "Alinhar ao início (vertical)",
  "align-vertical-distribute-center": "Distribuir na vertical pelo centro",
  "align-vertical-distribute-end": "Distribuir na vertical pelo fim",
  "align-vertical-distribute-start": "Distribuir na vertical pelo início",
  "align-vertical-justify-center": "Justificar na vertical ao centro",
  "align-vertical-justify-end": "Justificar na vertical ao fim",
  "align-vertical-justify-start": "Justificar na vertical ao início",
  "align-vertical-space-around": "Espaçar em volta (vertical)",
  "align-vertical-space-between": "Espaçar entre (vertical)",
  "ambulance": "Ambulância",
  "ampersand": "E comercial",
  "ampersands": "E comercial duplo",
  "anchor": "Âncora",
  "angry": "Rosto bravo",
  "annoyed": "Rosto irritado",
  "antenna": "Antena",
  "anvil": "Bigorna",
  "aperture": "Abertura da câmera",
  "app-window": "Janela de aplicativo",
  "app-window-mac": "Janela de aplicativo (Mac)",
  "apple": "Maçã",
  "archive": "Arquivo morto",
  "archive-restore": "Restaurar do arquivo",
  "archive-x": "Arquivo morto com X",
  "area-chart": "Gráfico de área",
  "armchair": "Poltrona",
  "arrow-big-down": "Seta grande para baixo",
  "arrow-big-down-dash": "Seta grande para baixo com traço",
  "arrow-big-left": "Seta grande para a esquerda",
  "arrow-big-left-dash": "Seta grande para a esquerda com traço",
  "arrow-big-right": "Seta grande para a direita",
  "arrow-big-right-dash": "Seta grande para a direita com traço",
  "arrow-big-up": "Seta grande para cima",
  "arrow-big-up-dash": "Seta grande para cima com traço",
  "arrow-down": "Seta para baixo",
  "arrow-down-0-1": "Ordenar de 0 a 9 (para baixo)",
  "arrow-down-1-0": "Ordenar de 9 a 0 (para baixo)",
  "arrow-down-a-z": "Ordenar de A a Z (para baixo)",
  "arrow-down-from-line": "Seta para baixo saindo da linha",
  "arrow-down-left": "Seta para baixo e à esquerda",
  "arrow-down-narrow-wide": "Ordenar do menor ao maior (para baixo)",
  "arrow-down-right": "Seta para baixo e à direita",
  "arrow-down-to-dot": "Seta para baixo até o ponto",
  "arrow-down-to-line": "Seta para baixo até a linha",
  "arrow-down-up": "Setas para baixo e para cima",
  "arrow-down-wide-narrow": "Ordenar do maior ao menor (para baixo)",
  "arrow-down-z-a": "Ordenar de Z a A (para baixo)",
  "arrow-left": "Seta para a esquerda",
  "arrow-left-from-line": "Seta para a esquerda saindo da linha",
  "arrow-left-right": "Setas para a esquerda e para a direita",
  "arrow-left-to-line": "Seta para a esquerda até a linha",
  "arrow-right": "Seta para a direita",
  "arrow-right-from-line": "Seta para a direita saindo da linha",
  "arrow-right-left": "Setas para a direita e para a esquerda",
  "arrow-right-to-line": "Seta para a direita até a linha",
  "arrow-up": "Seta para cima",
  "arrow-up-0-1": "Ordenar de 0 a 9 (para cima)",
  "arrow-up-1-0": "Ordenar de 9 a 0 (para cima)",
  "arrow-up-a-z": "Ordenar de A a Z (para cima)",
  "arrow-up-down": "Setas para cima e para baixo",
  "arrow-up-from-dot": "Seta para cima saindo do ponto",
  "arrow-up-from-line": "Seta para cima saindo da linha",
  "arrow-up-left": "Seta para cima e à esquerda",
  "arrow-up-narrow-wide": "Ordenar do menor ao maior (para cima)",
  "arrow-up-right": "Seta para cima e à direita",
  "arrow-up-to-line": "Seta para cima até a linha",
  "arrow-up-wide-narrow": "Ordenar do maior ao menor (para cima)",
  "arrow-up-z-a": "Ordenar de Z a A (para cima)",
  "arrows-up-from-line": "Setas para cima saindo da linha",
  "asterisk": "Asterisco",
  "at-sign": "Arroba",
  "atom": "Átomo",
  "audio-lines": "Linhas de áudio",
  "audio-waveform": "Onda de áudio",
  "award": "Prêmio",
  "axe": "Machado",
  "axis-3d": "Eixos 3D",
  "baby": "Bebê",
  "backpack": "Mochila",
  "badge": "Selo",
  "badge-alert": "Selo com alerta",
  "badge-cent": "Selo com centavo",
  "badge-check": "Selo com visto",
  "badge-dollar-sign": "Selo com cifrão",
  "badge-euro": "Selo com euro",
  "badge-help": "Selo com interrogação",
  "badge-indian-rupee": "Selo com rupia",
  "badge-info": "Selo com informação",
  "badge-japanese-yen": "Selo com iene",
  "badge-minus": "Selo com menos",
  "badge-percent": "Selo com porcentagem",
  "badge-plus": "Selo com mais",
  "badge-pound-sterling": "Selo com libra",
  "badge-russian-ruble": "Selo com rublo",
  "badge-swiss-franc": "Selo com franco suíço",
  "badge-x": "Selo com X",
  "baggage-claim": "Esteira de bagagem",
  "ban": "Proibido",
  "banana": "Banana",
  "banknote": "Cédula",
  "bar-chart": "Gráfico de barras",
  "bar-chart-2": "Gráfico de barras 2",
  "bar-chart-3": "Gráfico de barras 3",
  "bar-chart-4": "Gráfico de barras 4",
  "bar-chart-big": "Gráfico de barras grande",
  "bar-chart-horizontal": "Gráfico de barras horizontal",
  "bar-chart-horizontal-big": "Gráfico de barras horizontal grande",
  "barcode": "Código de barras",
  "baseline": "Linha de base",
  "bath": "Banheira",
  "battery": "Bateria",
  "battery-charging": "Bateria carregando",
  "battery-full": "Bateria cheia",
  "battery-low": "Bateria fraca",
  "battery-medium": "Bateria pela metade",
  "battery-warning": "Bateria com alerta",
  "beaker": "Béquer",
  "bean": "Grão",
  "bean-off": "Grão cortado",
  "bed": "Cama",
  "bed-double": "Cama de casal",
  "bed-single": "Cama de solteiro",
  "beef": "Carne",
  "beer": "Cerveja",
  "beer-off": "Cerveja cortada",
  "bell": "Sino",
  "bell-dot": "Sino com ponto",
  "bell-electric": "Campainha elétrica",
  "bell-minus": "Sino com menos",
  "bell-off": "Sino desligado",
  "bell-plus": "Sino com mais",
  "bell-ring": "Sino tocando",
  "between-horizontal-end": "Inserir entre (horizontal, fim)",
  "between-horizontal-start": "Inserir entre (horizontal, início)",
  "between-vertical-end": "Inserir entre (vertical, fim)",
  "between-vertical-start": "Inserir entre (vertical, início)",
  "biceps-flexed": "Bíceps",
  "bike": "Bicicleta",
  "binary": "Código binário",
  "biohazard": "Risco biológico",
  "bird": "Pássaro",
  "bitcoin": "Bitcoin",
  "blend": "Mesclar",
  "blinds": "Persiana",
  "blocks": "Blocos",
  "bluetooth": "Bluetooth",
  "bluetooth-connected": "Bluetooth conectado",
  "bluetooth-off": "Bluetooth desligado",
  "bluetooth-searching": "Bluetooth procurando",
  "bold": "Negrito",
  "bolt": "Raio",
  "bomb": "Bomba",
  "bone": "Osso",
  "book": "Livro",
  "book-a": "Livro com A",
  "book-audio": "Audiolivro",
  "book-check": "Livro com visto",
  "book-copy": "Livros copiados",
  "book-dashed": "Livro tracejado",
  "book-down": "Livro com seta para baixo",
  "book-headphones": "Livro com fones",
  "book-heart": "Livro com coração",
  "book-image": "Livro com imagem",
  "book-key": "Livro com chave",
  "book-lock": "Livro com cadeado",
  "book-marked": "Livro marcado",
  "book-minus": "Livro com menos",
  "book-open": "Livro aberto",
  "book-open-check": "Livro aberto com visto",
  "book-open-text": "Livro aberto com texto",
  "book-plus": "Livro com mais",
  "book-text": "Livro com texto",
  "book-type": "Livro com letra",
  "book-up": "Livro com seta para cima",
  "book-up-2": "Livro com seta para cima 2",
  "book-user": "Livro com pessoa",
  "book-x": "Livro com X",
  "bookmark": "Marcador",
  "bookmark-check": "Marcador com visto",
  "bookmark-minus": "Marcador com menos",
  "bookmark-plus": "Marcador com mais",
  "bookmark-x": "Marcador com X",
  "boom-box": "Aparelho de som",
  "bot": "Robô",
  "bot-message-square": "Robô com mensagem",
  "bot-off": "Robô desligado",
  "box": "Caixa",
  "box-select": "Seleção retangular",
  "boxes": "Caixas",
  "braces": "Chaves de código",
  "brackets": "Colchetes",
  "brain": "Cérebro",
  "brain-circuit": "Cérebro com circuito",
  "brain-cog": "Cérebro com engrenagem",
  "brick-wall": "Muro de tijolos",
  "briefcase": "Maleta",
  "briefcase-business": "Maleta de negócios",
  "briefcase-medical": "Maleta médica",
  "bring-to-front": "Trazer para a frente",
  "brush": "Pincel largo",
  "bug": "Inseto",
  "bug-off": "Inseto cortado",
  "bug-play": "Inseto com play",
  "building": "Prédio",
  "building-2": "Prédio 2",
  "bus": "Ônibus",
  "bus-front": "Ônibus de frente",
  "cable": "Cabo",
  "cable-car": "Teleférico",
  "cake": "Bolo",
  "cake-slice": "Fatia de bolo",
  "calculator": "Calculadora",
  "calendar": "Calendário",
  "calendar-arrow-down": "Calendário com seta para baixo",
  "calendar-arrow-up": "Calendário com seta para cima",
  "calendar-check": "Calendário com visto",
  "calendar-check-2": "Calendário com visto 2",
  "calendar-clock": "Calendário com relógio",
  "calendar-cog": "Calendário com engrenagem",
  "calendar-days": "Calendário com dias",
  "calendar-fold": "Calendário dobrado",
  "calendar-heart": "Calendário com coração",
  "calendar-minus": "Calendário com menos",
  "calendar-minus-2": "Calendário com menos 2",
  "calendar-off": "Calendário desligado",
  "calendar-plus": "Calendário com mais",
  "calendar-plus-2": "Calendário com mais 2",
  "calendar-range": "Calendário com período",
  "calendar-search": "Calendário com lupa",
  "calendar-x": "Calendário com X",
  "calendar-x-2": "Calendário com X 2",
  "camera": "Câmera",
  "camera-off": "Câmera desligada",
  "candlestick-chart": "Gráfico de velas",
  "candy": "Bala",
  "candy-cane": "Bengala de doce",
  "candy-off": "Bala cortada",
  "cannabis": "Cannabis",
  "captions": "Legendas",
  "captions-off": "Legendas desligadas",
  "car": "Carro",
  "car-front": "Carro de frente",
  "car-taxi-front": "Táxi",
  "caravan": "Trailer",
  "carrot": "Cenoura",
  "case-lower": "Letras minúsculas",
  "case-sensitive": "Maiúsculas e minúsculas",
  "case-upper": "Letras maiúsculas",
  "cassette-tape": "Fita cassete",
  "cast": "Transmitir",
  "castle": "Castelo",
  "cat": "Gato",
  "cctv": "Câmera de segurança",
  "check": "Visto",
  "check-check": "Dois vistos",
  "check-circle": "Confirmado",
  "chef-hat": "Chapéu de chef",
  "cherry": "Cereja",
  "chevron-down": "Divisa para baixo",
  "chevron-first": "Divisa até o início",
  "chevron-last": "Divisa até o fim",
  "chevron-left": "Divisa para a esquerda",
  "chevron-right": "Divisa para a direita",
  "chevron-up": "Divisa para cima",
  "chevrons-down": "Divisas duplas para baixo",
  "chevrons-down-up": "Divisas recolher",
  "chevrons-left": "Divisas duplas para a esquerda",
  "chevrons-left-right": "Divisas expandir na horizontal",
  "chevrons-right": "Divisas duplas para a direita",
  "chevrons-right-left": "Divisas recolher na horizontal",
  "chevrons-up": "Divisas duplas para cima",
  "chevrons-up-down": "Divisas expandir",
  "chrome": "Chrome",
  "church": "Igreja",
  "cigarette": "Cigarro",
  "cigarette-off": "Proibido fumar",
  "circle": "Círculo",
  "circle-alert": "Círculo com alerta",
  "circle-arrow-down": "Círculo com seta para baixo",
  "circle-arrow-left": "Círculo com seta para a esquerda",
  "circle-arrow-out-down-left": "Seta saindo do círculo (baixo, esquerda)",
  "circle-arrow-out-down-right": "Seta saindo do círculo (baixo, direita)",
  "circle-arrow-out-up-left": "Seta saindo do círculo (cima, esquerda)",
  "circle-arrow-out-up-right": "Seta saindo do círculo (cima, direita)",
  "circle-arrow-right": "Círculo com seta para a direita",
  "circle-arrow-up": "Círculo com seta para cima",
  "circle-check": "Círculo com visto",
  "circle-check-big": "Círculo com visto grande",
  "circle-chevron-down": "Círculo com divisa para baixo",
  "circle-chevron-left": "Círculo com divisa para a esquerda",
  "circle-chevron-right": "Círculo com divisa para a direita",
  "circle-chevron-up": "Círculo com divisa para cima",
  "circle-dashed": "Círculo tracejado",
  "circle-divide": "Círculo com divisão",
  "circle-dollar-sign": "Círculo com cifrão",
  "circle-dot": "Círculo com ponto",
  "circle-dot-dashed": "Círculo tracejado com ponto",
  "circle-ellipsis": "Círculo com reticências",
  "circle-equal": "Círculo com igual",
  "circle-fading-plus": "Círculo com mais esmaecido",
  "circle-gauge": "Velocímetro redondo",
  "circle-help": "Círculo com interrogação",
  "circle-minus": "Círculo com menos",
  "circle-off": "Círculo desligado",
  "circle-parking": "Estacionamento",
  "circle-parking-off": "Estacionamento proibido",
  "circle-pause": "Círculo com pausa",
  "circle-percent": "Círculo com porcentagem",
  "circle-play": "Círculo com play",
  "circle-plus": "Círculo com mais",
  "circle-power": "Círculo com botão liga/desliga",
  "circle-slash": "Círculo cortado",
  "circle-slash-2": "Círculo cortado 2",
  "circle-stop": "Círculo com parar",
  "circle-user": "Usuário no círculo",
  "circle-user-round": "Usuário no círculo (arredondado)",
  "circle-x": "Círculo com X",
  "circuit-board": "Placa de circuito",
  "citrus": "Limão",
  "clapperboard": "Claquete",
  "clipboard": "Prancheta",
  "clipboard-check": "Prancheta com visto",
  "clipboard-copy": "Prancheta copiar",
  "clipboard-list": "Prancheta com lista",
  "clipboard-minus": "Prancheta com menos",
  "clipboard-paste": "Prancheta colar",
  "clipboard-pen": "Prancheta com caneta",
  "clipboard-pen-line": "Prancheta com caneta e linha",
  "clipboard-plus": "Prancheta com mais",
  "clipboard-type": "Prancheta com letra",
  "clipboard-x": "Prancheta com X",
  "clock": "Relógio",
  "clock-1": "Relógio 1h",
  "clock-10": "Relógio 10h",
  "clock-11": "Relógio 11h",
  "clock-12": "Relógio 12h",
  "clock-2": "Relógio 2h",
  "clock-3": "Relógio 3h",
  "clock-4": "Relógio 4h",
  "clock-5": "Relógio 5h",
  "clock-6": "Relógio 6h",
  "clock-7": "Relógio 7h",
  "clock-8": "Relógio 8h",
  "clock-9": "Relógio 9h",
  "clock-arrow-down": "Relógio com seta para baixo",
  "clock-arrow-up": "Relógio com seta para cima",
  "cloud": "Nuvem",
  "cloud-cog": "Nuvem com engrenagem",
  "cloud-download": "Nuvem com download",
  "cloud-drizzle": "Garoa",
  "cloud-fog": "Neblina",
  "cloud-hail": "Granizo",
  "cloud-lightning": "Tempestade",
  "cloud-moon": "Nuvem e lua",
  "cloud-moon-rain": "Chuva à noite",
  "cloud-off": "Nuvem desligada",
  "cloud-rain": "Chuva",
  "cloud-rain-wind": "Chuva com vento",
  "cloud-snow": "Neve",
  "cloud-sun": "Sol entre nuvens",
  "cloud-sun-rain": "Sol e chuva",
  "cloud-upload": "Nuvem com upload",
  "cloudy": "Nublado",
  "clover": "Trevo",
  "club": "Paus (naipe)",
  "code": "Código",
  "code-xml": "Código XML",
  "codepen": "CodePen",
  "codesandbox": "CodeSandbox",
  "coffee": "Café",
  "cog": "Engrenagem dentada",
  "coins": "Moedas",
  "columns-2": "Duas colunas",
  "columns-3": "Três colunas",
  "columns-4": "Quatro colunas",
  "combine": "Combinar",
  "command": "Command (tecla)",
  "compass": "Bússola",
  "component": "Componente",
  "computer": "Computador",
  "concierge-bell": "Campainha de balcão",
  "cone": "Cone",
  "construction": "Construção",
  "contact": "Contato",
  "contact-round": "Contato (arredondado)",
  "container": "Contêiner",
  "contrast": "Contraste",
  "cookie": "Biscoito",
  "cooking-pot": "Panela",
  "copy": "Copiar",
  "copy-check": "Copiar com visto",
  "copy-minus": "Copiar com menos",
  "copy-plus": "Copiar com mais",
  "copy-slash": "Copiar cortado",
  "copy-x": "Copiar com X",
  "copyleft": "Copyleft",
  "copyright": "Direitos autorais",
  "corner-down-left": "Canto para baixo e à esquerda",
  "corner-down-right": "Canto para baixo e à direita",
  "corner-left-down": "Canto à esquerda e para baixo",
  "corner-left-up": "Canto à esquerda e para cima",
  "corner-right-down": "Canto à direita e para baixo",
  "corner-right-up": "Canto à direita e para cima",
  "corner-up-left": "Canto para cima e à esquerda",
  "corner-up-right": "Canto para cima e à direita",
  "cpu": "Processador",
  "creative-commons": "Creative Commons",
  "credit-card": "Cartão de crédito",
  "croissant": "Croissant",
  "crop": "Recortar",
  "cross": "Cruz",
  "crosshair": "Mira",
  "crown": "Coroa",
  "cuboid": "Cubo retangular",
  "cup-soda": "Copo de refrigerante",
  "currency": "Moeda (símbolo)",
  "cylinder": "Cilindro",
  "database": "Banco de dados",
  "database-backup": "Backup do banco de dados",
  "database-zap": "Banco de dados com raio",
  "delete": "Apagar (tecla)",
  "dessert": "Sobremesa",
  "diameter": "Diâmetro",
  "diamond": "Losango",
  "diamond-minus": "Losango com menos",
  "diamond-percent": "Losango com porcentagem",
  "diamond-plus": "Losango com mais",
  "dice-1": "Dado 1",
  "dice-2": "Dado 2",
  "dice-3": "Dado 3",
  "dice-4": "Dado 4",
  "dice-5": "Dado 5",
  "dice-6": "Dado 6",
  "dices": "Dados (jogo)",
  "diff": "Diferença",
  "disc": "Disco",
  "disc-2": "Disco 2",
  "disc-3": "Disco 3",
  "disc-album": "Disco de álbum",
  "divide": "Dividir",
  "dna": "DNA",
  "dna-off": "DNA cortado",
  "dock": "Dock",
  "dog": "Cachorro",
  "dollar-sign": "Cifrão",
  "donut": "Rosquinha",
  "door-closed": "Porta fechada",
  "door-open": "Porta aberta",
  "dot": "Ponto",
  "download": "Baixar",
  "drafting-compass": "Compasso",
  "drama": "Máscaras de teatro",
  "dribbble": "Dribbble",
  "drill": "Furadeira",
  "droplet": "Gota",
  "droplets": "Gotas",
  "drum": "Tambor",
  "drumstick": "Coxa de frango",
  "dumbbell": "Halter",
  "ear": "Orelha",
  "ear-off": "Orelha cortada",
  "earth": "Planeta Terra",
  "earth-lock": "Terra com cadeado",
  "eclipse": "Eclipse",
  "egg": "Ovo",
  "egg-fried": "Ovo frito",
  "egg-off": "Ovo cortado",
  "ellipsis": "Reticências",
  "ellipsis-vertical": "Reticências verticais",
  "equal": "Igual",
  "equal-not": "Diferente",
  "eraser": "Borracha",
  "euro": "Euro",
  "expand": "Expandir",
  "external-link": "Link externo",
  "eye": "Olho",
  "eye-off": "Olho cortado",
  "facebook": "Facebook",
  "factory": "Fábrica",
  "fan": "Ventilador",
  "fast-forward": "Avançar rápido",
  "feather": "Pena",
  "fence": "Cerca",
  "ferris-wheel": "Roda-gigante",
  "figma": "Figma",
  "file": "Arquivo",
  "file-archive": "Arquivo compactado",
  "file-audio": "Arquivo de áudio",
  "file-audio-2": "Arquivo de áudio 2",
  "file-axis-3d": "Arquivo 3D",
  "file-badge": "Arquivo com selo",
  "file-badge-2": "Arquivo com selo 2",
  "file-bar-chart": "Arquivo com gráfico de barras",
  "file-bar-chart-2": "Arquivo com gráfico de barras 2",
  "file-box": "Arquivo com caixa",
  "file-check": "Arquivo com visto",
  "file-check-2": "Arquivo com visto 2",
  "file-clock": "Arquivo com relógio",
  "file-code": "Arquivo de código",
  "file-code-2": "Arquivo de código 2",
  "file-cog": "Arquivo com engrenagem",
  "file-diff": "Arquivo com diferenças",
  "file-digit": "Arquivo com números",
  "file-down": "Arquivo com seta para baixo",
  "file-heart": "Arquivo com coração",
  "file-image": "Arquivo de imagem",
  "file-input": "Arquivo de entrada",
  "file-json": "Arquivo JSON",
  "file-json-2": "Arquivo JSON 2",
  "file-key": "Arquivo com chave",
  "file-key-2": "Arquivo com chave 2",
  "file-line-chart": "Arquivo com gráfico de linha",
  "file-lock": "Arquivo com cadeado",
  "file-lock-2": "Arquivo com cadeado 2",
  "file-minus": "Arquivo com menos",
  "file-minus-2": "Arquivo com menos 2",
  "file-music": "Arquivo de música",
  "file-output": "Arquivo de saída",
  "file-pen": "Arquivo com caneta",
  "file-pen-line": "Arquivo com caneta e linha",
  "file-pie-chart": "Arquivo com gráfico de pizza",
  "file-plus": "Arquivo com mais",
  "file-plus-2": "Arquivo com mais 2",
  "file-question": "Arquivo com interrogação",
  "file-scan": "Arquivo digitalizado",
  "file-search": "Arquivo com lupa",
  "file-search-2": "Arquivo com lupa 2",
  "file-sliders": "Arquivo com controles",
  "file-spreadsheet": "Planilha",
  "file-stack": "Pilha de arquivos",
  "file-symlink": "Atalho de arquivo",
  "file-terminal": "Arquivo de terminal",
  "file-text": "Documento",
  "file-type": "Arquivo com letra",
  "file-type-2": "Arquivo com letra 2",
  "file-up": "Arquivo com seta para cima",
  "file-video": "Arquivo de vídeo",
  "file-video-2": "Arquivo de vídeo 2",
  "file-volume": "Arquivo com som",
  "file-volume-2": "Arquivo com som 2",
  "file-warning": "Arquivo com alerta",
  "file-x": "Arquivo com X",
  "file-x-2": "Arquivo com X 2",
  "files": "Arquivos",
  "film": "Filme",
  "filter": "Filtro",
  "filter-x": "Filtro com X",
  "fingerprint": "Impressão digital",
  "fire-extinguisher": "Extintor",
  "fish": "Peixe",
  "fish-off": "Peixe cortado",
  "fish-symbol": "Símbolo de peixe",
  "flag": "Bandeira",
  "flag-off": "Bandeira cortada",
  "flag-triangle-left": "Bandeirola para a esquerda",
  "flag-triangle-right": "Bandeirola para a direita",
  "flame": "Chama",
  "flame-kindling": "Fogueira",
  "flashlight": "Lanterna",
  "flashlight-off": "Lanterna desligada",
  "flask-conical": "Frasco cônico",
  "flask-conical-off": "Frasco cônico cortado",
  "flask-round": "Frasco redondo",
  "flip-horizontal": "Espelhar na horizontal",
  "flip-horizontal-2": "Espelhar na horizontal 2",
  "flip-vertical": "Espelhar na vertical",
  "flip-vertical-2": "Espelhar na vertical 2",
  "flower": "Flor",
  "flower-2": "Flor 2",
  "focus": "Foco",
  "fold-horizontal": "Recolher na horizontal",
  "fold-vertical": "Recolher na vertical",
  "folder": "Pasta",
  "folder-archive": "Pasta compactada",
  "folder-check": "Pasta com visto",
  "folder-clock": "Pasta com relógio",
  "folder-closed": "Pasta fechada",
  "folder-code": "Pasta de código",
  "folder-cog": "Pasta com engrenagem",
  "folder-dot": "Pasta com ponto",
  "folder-down": "Pasta com seta para baixo",
  "folder-git": "Pasta Git",
  "folder-git-2": "Pasta Git 2",
  "folder-heart": "Pasta com coração",
  "folder-input": "Pasta de entrada",
  "folder-kanban": "Pasta com kanban",
  "folder-key": "Pasta com chave",
  "folder-lock": "Pasta com cadeado",
  "folder-minus": "Pasta com menos",
  "folder-open": "Pasta aberta",
  "folder-open-dot": "Pasta aberta com ponto",
  "folder-output": "Pasta de saída",
  "folder-pen": "Pasta com caneta",
  "folder-plus": "Pasta com mais",
  "folder-root": "Pasta raiz",
  "folder-search": "Pasta com lupa",
  "folder-search-2": "Pasta com lupa 2",
  "folder-symlink": "Atalho de pasta",
  "folder-sync": "Pasta sincronizando",
  "folder-tree": "Árvore de pastas",
  "folder-up": "Pasta com seta para cima",
  "folder-x": "Pasta com X",
  "folders": "Pastas",
  "footprints": "Pegadas",
  "forklift": "Empilhadeira",
  "forward": "Encaminhar",
  "frame": "Moldura",
  "framer": "Framer",
  "frown": "Rosto triste",
  "fuel": "Combustível",
  "fullscreen": "Tela cheia",
  "gallery-horizontal": "Galeria horizontal",
  "gallery-horizontal-end": "Galeria horizontal (fim)",
  "gallery-thumbnails": "Galeria de miniaturas",
  "gallery-vertical": "Galeria vertical",
  "gallery-vertical-end": "Galeria vertical (fim)",
  "gamepad": "Controle de videogame",
  "gamepad-2": "Controle de videogame 2",
  "gantt-chart": "Gráfico de Gantt",
  "gauge": "Velocímetro",
  "gavel": "Martelo de juiz",
  "gem": "Joia",
  "ghost": "Fantasma",
  "gift": "Presente",
  "git-branch": "Ramificação",
  "git-branch-plus": "Nova ramificação Git",
  "git-commit-horizontal": "Commit Git (horizontal)",
  "git-commit-vertical": "Commit Git (vertical)",
  "git-compare": "Comparar no Git",
  "git-compare-arrows": "Comparar no Git com setas",
  "git-fork": "Fork Git",
  "git-graph": "Gráfico do Git",
  "git-merge": "Merge Git",
  "git-pull-request": "Pull request",
  "git-pull-request-arrow": "Pull request com seta",
  "git-pull-request-closed": "Pull request fechado",
  "git-pull-request-create": "Criar pull request",
  "git-pull-request-create-arrow": "Criar pull request com seta",
  "git-pull-request-draft": "Pull request em rascunho",
  "github": "GitHub",
  "gitlab": "GitLab",
  "glass-water": "Copo d'água",
  "glasses": "Óculos",
  "globe": "Globo",
  "globe-lock": "Globo com cadeado",
  "goal": "Gol",
  "grab": "Mão agarrando",
  "graduation-cap": "Capelo de formatura",
  "grape": "Uva",
  "grid-2x2": "Grade 2x2",
  "grid-2x2-check": "Grade 2x2 com visto",
  "grid-2x2-x": "Grade 2x2 com X",
  "grid-3x3": "Grade 3x3",
  "grip": "Alça",
  "grip-horizontal": "Alça horizontal",
  "grip-vertical": "Alça vertical",
  "group": "Agrupar",
  "guitar": "Violão",
  "ham": "Presunto",
  "hammer": "Martelo",
  "hand": "Mão",
  "hand-coins": "Mão com moedas",
  "hand-heart": "Mão com coração",
  "hand-helping": "Mão ajudando",
  "hand-metal": "Mão do rock",
  "hand-platter": "Mão com bandeja",
  "handshake": "Aperto de mãos",
  "hard-drive": "Disco rígido",
  "hard-drive-download": "Disco rígido com download",
  "hard-drive-upload": "Disco rígido com upload",
  "hard-hat": "Capacete de obra",
  "hash": "Cerquilha",
  "haze": "Névoa",
  "hdmi-port": "Porta HDMI",
  "heading": "Título",
  "heading-1": "Título 1",
  "heading-2": "Título 2",
  "heading-3": "Título 3",
  "heading-4": "Título 4",
  "heading-5": "Título 5",
  "heading-6": "Título 6",
  "headphones": "Fones de ouvido",
  "headset": "Headset",
  "heart": "Coração",
  "heart-crack": "Coração partido",
  "heart-handshake": "Coração com aperto de mãos",
  "heart-off": "Coração cortado",
  "heart-pulse": "Coração com batimento",
  "heater": "Aquecedor",
  "hexagon": "Hexágono",
  "highlighter": "Marca-texto",
  "history": "Histórico",
  "hop": "Lúpulo",
  "hop-off": "Lúpulo cortado",
  "hospital": "Hospital",
  "hotel": "Hotel",
  "hourglass": "Ampulheta",
  "house": "Casa",
  "house-plug": "Casa com tomada",
  "house-plus": "Casa com mais",
  "ice-cream-bowl": "Taça de sorvete",
  "ice-cream-cone": "Casquinha de sorvete",
  "image": "Imagem",
  "image-down": "Imagem com seta para baixo",
  "image-minus": "Imagem com menos",
  "image-off": "Imagem desligada",
  "image-play": "Imagem com play",
  "image-plus": "Imagem com mais",
  "image-up": "Imagem com seta para cima",
  "images": "Imagens",
  "import": "Importar",
  "inbox": "Caixa de entrada",
  "indent-decrease": "Diminuir recuo",
  "indent-increase": "Aumentar recuo",
  "indian-rupee": "Rupia indiana",
  "infinity": "Infinito",
  "info": "Informação",
  "inspection-panel": "Painel de inspeção",
  "instagram": "Instagram",
  "italic": "Itálico",
  "iteration-ccw": "Iteração (anti-horário)",
  "iteration-cw": "Iteração (horário)",
  "japanese-yen": "Iene",
  "joystick": "Joystick",
  "kanban": "Kanban",
  "key": "Chave",
  "key-round": "Chave (arredondada)",
  "key-square": "Chave (quadrada)",
  "keyboard": "Teclado",
  "keyboard-music": "Teclado musical",
  "keyboard-off": "Teclado desligado",
  "lamp": "Abajur",
  "lamp-ceiling": "Luminária de teto",
  "lamp-desk": "Luminária de mesa",
  "lamp-floor": "Luminária de chão",
  "lamp-wall-down": "Arandela para baixo",
  "lamp-wall-up": "Arandela para cima",
  "land-plot": "Terreno",
  "landmark": "Monumento",
  "languages": "Idiomas",
  "laptop": "Notebook",
  "laptop-minimal": "Notebook simples",
  "lasso": "Laço",
  "lasso-select": "Seleção com laço",
  "laugh": "Rosto rindo",
  "layers": "Camadas (Lucide)",
  "layers-2": "Camadas 2",
  "layers-3": "Pilha",
  "layout-dashboard": "Painel",
  "layout-grid": "Layout em grade",
  "layout-list": "Layout em lista",
  "layout-panel-left": "Layout com painel à esquerda",
  "layout-panel-top": "Layout com painel no topo",
  "layout-template": "Modelo de layout",
  "leaf": "Folha",
  "leafy-green": "Verdura",
  "lectern": "Púlpito",
  "library": "Biblioteca",
  "library-big": "Biblioteca grande",
  "life-buoy": "Boia salva-vidas",
  "ligature": "Ligadura",
  "lightbulb": "Lâmpada",
  "lightbulb-off": "Lâmpada apagada",
  "line-chart": "Gráfico de linha",
  "link": "Link",
  "link-2": "Link 2",
  "link-2-off": "Link cortado 2",
  "linkedin": "LinkedIn",
  "list": "Lista",
  "list-check": "Lista com visto",
  "list-checks": "Checklist",
  "list-collapse": "Recolher lista",
  "list-end": "Fim da lista",
  "list-filter": "Lista filtrada",
  "list-minus": "Lista com menos",
  "list-music": "Lista de músicas",
  "list-ordered": "Lista numerada",
  "list-plus": "Lista com mais",
  "list-restart": "Reiniciar lista",
  "list-start": "Início da lista",
  "list-todo": "Lista de tarefas",
  "list-tree": "Lista em árvore",
  "list-video": "Lista de vídeos",
  "list-x": "Lista com X",
  "loader": "Carregando",
  "loader-circle": "Carregando (círculo)",
  "loader-pinwheel": "Carregando (cata-vento)",
  "locate": "Localizar",
  "locate-fixed": "Localização fixa",
  "locate-off": "Localização desligada",
  "lock": "Cadeado",
  "lock-keyhole": "Cadeado com fechadura",
  "lock-keyhole-open": "Cadeado aberto com fechadura",
  "lock-open": "Cadeado aberto",
  "log-in": "Entrar",
  "log-out": "Sair",
  "logs": "Registros",
  "lollipop": "Pirulito",
  "luggage": "Mala",
  "magnet": "Ímã",
  "mail": "E-mail",
  "mail-check": "E-mail com visto",
  "mail-minus": "E-mail com menos",
  "mail-open": "E-mail aberto",
  "mail-plus": "E-mail com mais",
  "mail-question": "E-mail com interrogação",
  "mail-search": "E-mail com lupa",
  "mail-warning": "E-mail com alerta",
  "mail-x": "E-mail com X",
  "mailbox": "Caixa de correio",
  "mails": "E-mails",
  "map": "Mapa",
  "map-pin": "Marcador de mapa",
  "map-pin-off": "Marcador de mapa desligado",
  "map-pinned": "Mapa com marcador",
  "martini": "Martíni",
  "maximize": "Maximizar",
  "maximize-2": "Maximizar 2",
  "medal": "Medalha",
  "megaphone": "Megafone",
  "megaphone-off": "Megafone desligado",
  "meh": "Rosto indiferente",
  "memory-stick": "Memória RAM",
  "menu": "Menu",
  "merge": "Juntar",
  "message-circle": "Balão de conversa",
  "message-circle-code": "Balão com código",
  "message-circle-dashed": "Balão tracejado",
  "message-circle-heart": "Balão com coração",
  "message-circle-more": "Balão com reticências",
  "message-circle-off": "Balão desligado",
  "message-circle-plus": "Balão com mais",
  "message-circle-question": "Balão com interrogação",
  "message-circle-reply": "Balão de resposta",
  "message-circle-warning": "Balão com alerta",
  "message-circle-x": "Balão com X",
  "message-square": "Mensagem",
  "message-square-code": "Mensagem com código",
  "message-square-dashed": "Mensagem tracejada",
  "message-square-diff": "Mensagem com diferença",
  "message-square-dot": "Mensagem com ponto",
  "message-square-heart": "Mensagem com coração",
  "message-square-more": "Mensagem com reticências",
  "message-square-off": "Mensagem desligada",
  "message-square-plus": "Mensagem com mais",
  "message-square-quote": "Mensagem com citação",
  "message-square-reply": "Mensagem de resposta",
  "message-square-share": "Mensagem compartilhada",
  "message-square-text": "Mensagem com texto",
  "message-square-warning": "Mensagem com alerta",
  "message-square-x": "Mensagem com X",
  "messages-square": "Mensagens",
  "mic": "Microfone",
  "mic-off": "Microfone desligado",
  "mic-vocal": "Microfone de mão",
  "microscope": "Microscópio",
  "microwave": "Micro-ondas",
  "milestone": "Marco",
  "milk": "Leite",
  "milk-off": "Leite cortado",
  "minimize": "Minimizar",
  "minimize-2": "Minimizar 2",
  "minus": "Menos",
  "monitor": "Monitor",
  "monitor-check": "Monitor com visto",
  "monitor-cog": "Monitor com engrenagem",
  "monitor-dot": "Monitor com ponto",
  "monitor-down": "Monitor com seta para baixo",
  "monitor-off": "Monitor desligado",
  "monitor-pause": "Monitor com pausa",
  "monitor-play": "Monitor com play",
  "monitor-smartphone": "Monitor e celular",
  "monitor-speaker": "Monitor e caixa de som",
  "monitor-stop": "Monitor com parar",
  "monitor-up": "Monitor com seta para cima",
  "monitor-x": "Monitor com X",
  "moon": "Lua",
  "moon-star": "Lua e estrela",
  "mountain": "Montanha",
  "mountain-snow": "Montanha com neve",
  "mouse": "Mouse",
  "mouse-off": "Mouse desligado",
  "mouse-pointer": "Ponteiro do mouse",
  "mouse-pointer-2": "Ponteiro do mouse 2",
  "mouse-pointer-ban": "Ponteiro proibido",
  "mouse-pointer-click": "Clique do mouse",
  "move": "Mover",
  "move-3d": "Mover em 3D",
  "move-diagonal": "Mover na diagonal",
  "move-diagonal-2": "Mover na diagonal 2",
  "move-down": "Mover para baixo",
  "move-down-left": "Mover para baixo e à esquerda",
  "move-down-right": "Mover para baixo e à direita",
  "move-horizontal": "Mover na horizontal",
  "move-left": "Mover para a esquerda",
  "move-right": "Mover para a direita",
  "move-up": "Mover para cima",
  "move-up-left": "Mover para cima e à esquerda",
  "move-up-right": "Mover para cima e à direita",
  "move-vertical": "Mover na vertical",
  "music": "Música",
  "music-2": "Nota musical 2",
  "music-3": "Nota musical 3",
  "music-4": "Notas musicais",
  "navigation": "Navegação",
  "navigation-2": "Navegação 2",
  "navigation-2-off": "Navegação desligada 2",
  "navigation-off": "Navegação desligada",
  "network": "Rede",
  "newspaper": "Jornal",
  "nfc": "NFC",
  "notebook": "Caderno",
  "notebook-pen": "Caderno com caneta",
  "notebook-tabs": "Caderno com abas",
  "notebook-text": "Caderno com texto",
  "notepad-text": "Bloco de notas",
  "notepad-text-dashed": "Bloco de notas tracejado",
  "nut": "Noz",
  "nut-off": "Noz cortada",
  "octagon": "Octógono",
  "octagon-alert": "Octógono com alerta",
  "octagon-pause": "Octógono com pausa",
  "octagon-x": "Octógono com X",
  "option": "Option (tecla)",
  "orbit": "Órbita",
  "origami": "Origami",
  "package": "Pacote",
  "package-2": "Pacote 2",
  "package-check": "Pacote com visto",
  "package-minus": "Pacote com menos",
  "package-open": "Pacote aberto",
  "package-plus": "Pacote com mais",
  "package-search": "Pacote com lupa",
  "package-x": "Pacote com X",
  "paint-bucket": "Balde de tinta",
  "paint-roller": "Rolo de pintura",
  "paintbrush": "Pincel",
  "paintbrush-vertical": "Pincel vertical",
  "palette": "Paleta de cores",
  "panel-bottom": "Painel inferior",
  "panel-bottom-close": "Fechar painel inferior",
  "panel-bottom-dashed": "Painel inferior tracejado",
  "panel-bottom-open": "Abrir painel inferior",
  "panel-left": "Painel esquerdo",
  "panel-left-close": "Fechar painel esquerdo",
  "panel-left-dashed": "Painel esquerdo tracejado",
  "panel-left-open": "Abrir painel esquerdo",
  "panel-right": "Painel direito",
  "panel-right-close": "Fechar painel direito",
  "panel-right-dashed": "Painel direito tracejado",
  "panel-right-open": "Abrir painel direito",
  "panel-top": "Painel superior",
  "panel-top-close": "Fechar painel superior",
  "panel-top-dashed": "Painel superior tracejado",
  "panel-top-open": "Abrir painel superior",
  "panels-left-bottom": "Painéis à esquerda e embaixo",
  "panels-right-bottom": "Painéis à direita e embaixo",
  "panels-top-left": "Painéis no topo e à esquerda",
  "paperclip": "Clipe de papel",
  "parentheses": "Parênteses",
  "parking-meter": "Parquímetro",
  "party-popper": "Lança-confete",
  "pause": "Pausa",
  "paw-print": "Pegada de animal",
  "pc-case": "Gabinete de computador",
  "pen": "Caneta (escrita)",
  "pen-line": "Caneta com linha",
  "pen-off": "Caneta cortada",
  "pen-tool": "Caneta",
  "pencil": "Lápis",
  "pencil-line": "Lápis com linha",
  "pencil-off": "Lápis cortado",
  "pencil-ruler": "Lápis e régua",
  "pentagon": "Pentágono",
  "percent": "Porcentagem",
  "person-standing": "Pessoa em pé",
  "philippine-peso": "Peso filipino",
  "phone": "Telefone",
  "phone-call": "Telefone chamando",
  "phone-forwarded": "Chamada encaminhada",
  "phone-incoming": "Chamada recebida",
  "phone-missed": "Chamada perdida",
  "phone-off": "Telefone desligado",
  "phone-outgoing": "Chamada feita",
  "pi": "Pi",
  "piano": "Piano",
  "pickaxe": "Picareta",
  "picture-in-picture": "Imagem na imagem",
  "picture-in-picture-2": "Imagem na imagem 2",
  "pie-chart": "Gráfico de pizza",
  "piggy-bank": "Cofrinho",
  "pilcrow": "Parágrafo (símbolo)",
  "pilcrow-left": "Parágrafo à esquerda",
  "pilcrow-right": "Parágrafo à direita",
  "pill": "Comprimido",
  "pill-bottle": "Frasco de remédio",
  "pin": "Alfinete",
  "pin-off": "Alfinete cortado",
  "pipette": "Pipeta",
  "pizza": "Pizza",
  "plane": "Avião",
  "plane-landing": "Avião pousando",
  "plane-takeoff": "Avião decolando",
  "play": "Play",
  "plug": "Plugue",
  "plug-2": "Tomada 2",
  "plug-zap": "Tomada com raio",
  "plus": "Mais",
  "pocket": "Pocket",
  "pocket-knife": "Canivete",
  "podcast": "Podcast",
  "pointer": "Ponteiro (mão)",
  "pointer-off": "Ponteiro cortado",
  "popcorn": "Pipoca",
  "popsicle": "Picolé",
  "pound-sterling": "Libra esterlina",
  "power": "Liga/desliga",
  "power-off": "Desligar",
  "presentation": "Apresentação",
  "printer": "Impressora",
  "printer-check": "Impressora com visto",
  "projector": "Projetor",
  "proportions": "Proporções",
  "puzzle": "Quebra-cabeça",
  "pyramid": "Pirâmide",
  "qr-code": "QR code",
  "quote": "Aspas",
  "rabbit": "Coelho",
  "radar": "Radar",
  "radiation": "Radiação",
  "radical": "Raiz quadrada",
  "radio": "Rádio",
  "radio-receiver": "Rádio receptor",
  "radio-tower": "Torre de rádio",
  "radius": "Raio (medida)",
  "rail-symbol": "Símbolo de trem",
  "rainbow": "Arco-íris",
  "rat": "Rato",
  "ratio": "Proporção",
  "receipt": "Recibo",
  "receipt-cent": "Recibo com centavo",
  "receipt-euro": "Recibo com euro",
  "receipt-indian-rupee": "Recibo com rupia",
  "receipt-japanese-yen": "Recibo com iene",
  "receipt-pound-sterling": "Recibo com libra",
  "receipt-russian-ruble": "Recibo com rublo",
  "receipt-swiss-franc": "Recibo com franco suíço",
  "receipt-text": "Recibo com texto",
  "rectangle-ellipsis": "Retângulo com reticências",
  "rectangle-horizontal": "Retângulo horizontal",
  "rectangle-vertical": "Retângulo vertical",
  "recycle": "Reciclar",
  "redo": "Refazer",
  "redo-2": "Refazer 2",
  "redo-dot": "Refazer com ponto",
  "refresh-ccw": "Atualizar (anti-horário)",
  "refresh-ccw-dot": "Atualizar com ponto (anti-horário)",
  "refresh-cw": "Atualizar",
  "refresh-cw-off": "Atualizar desligado",
  "refrigerator": "Geladeira",
  "regex": "Expressão regular",
  "remove-formatting": "Remover formatação",
  "repeat": "Repetir",
  "repeat-1": "Repetir uma vez",
  "repeat-2": "Repetir 2",
  "replace": "Substituir",
  "replace-all": "Substituir tudo",
  "reply": "Responder",
  "reply-all": "Responder a todos",
  "rewind": "Voltar rápido",
  "ribbon": "Laço de fita",
  "rocket": "Foguete",
  "rocking-chair": "Cadeira de balanço",
  "roller-coaster": "Montanha-russa",
  "rotate-3d": "Girar em 3D",
  "rotate-ccw": "Girar (anti-horário)",
  "rotate-ccw-square": "Girar quadrado (anti-horário)",
  "rotate-cw": "Girar (horário)",
  "rotate-cw-square": "Girar quadrado (horário)",
  "route": "Rota",
  "route-off": "Rota cortada",
  "router": "Roteador",
  "rows-2": "Duas linhas",
  "rows-3": "Três linhas",
  "rows-4": "Quatro linhas",
  "rss": "RSS",
  "ruler": "Régua",
  "russian-ruble": "Rublo",
  "sailboat": "Veleiro",
  "salad": "Salada",
  "sandwich": "Sanduíche",
  "satellite": "Satélite",
  "satellite-dish": "Antena parabólica",
  "save": "Salvar",
  "save-all": "Salvar tudo",
  "save-off": "Salvar desligado",
  "scale": "Balança",
  "scale-3d": "Escala 3D",
  "scaling": "Redimensionar",
  "scan": "Escanear",
  "scan-barcode": "Escanear código de barras",
  "scan-eye": "Escanear olho",
  "scan-face": "Reconhecimento facial",
  "scan-line": "Escanear linha",
  "scan-qr-code": "Escanear QR code",
  "scan-search": "Escanear com lupa",
  "scan-text": "Escanear texto",
  "scatter-chart": "Gráfico de dispersão",
  "school": "Escola",
  "scissors": "Tesoura",
  "scissors-line-dashed": "Tesoura com linha tracejada",
  "screen-share": "Compartilhar tela",
  "screen-share-off": "Compartilhar tela desligado",
  "scroll": "Pergaminho",
  "scroll-text": "Pergaminho com texto",
  "search": "Lupa",
  "search-check": "Lupa com visto",
  "search-code": "Lupa com código",
  "search-slash": "Lupa cortada",
  "search-x": "Lupa com X",
  "section": "Parágrafo legal (§)",
  "send": "Enviar",
  "send-horizontal": "Enviar (horizontal)",
  "send-to-back": "Enviar para trás",
  "separator-horizontal": "Separador horizontal",
  "separator-vertical": "Separador vertical",
  "server": "Servidor",
  "server-cog": "Servidor com engrenagem",
  "server-crash": "Servidor com falha",
  "server-off": "Servidor desligado",
  "settings": "Engrenagem",
  "settings-2": "Ajustes",
  "shapes": "Formas",
  "share": "Compartilhar",
  "share-2": "Compartilhar 2",
  "sheet": "Planilha (folha)",
  "shell": "Concha",
  "shield": "Escudo",
  "shield-alert": "Escudo com alerta",
  "shield-ban": "Escudo proibido",
  "shield-check": "Escudo com visto",
  "shield-ellipsis": "Escudo com reticências",
  "shield-half": "Escudo pela metade",
  "shield-minus": "Escudo com menos",
  "shield-off": "Escudo desligado",
  "shield-plus": "Escudo com mais",
  "shield-question": "Escudo com interrogação",
  "shield-x": "Escudo com X",
  "ship": "Navio",
  "ship-wheel": "Leme",
  "shirt": "Camiseta",
  "shopping-bag": "Sacola de compras",
  "shopping-basket": "Cesta de compras",
  "shopping-cart": "Carrinho de compras",
  "shovel": "Pá",
  "shower-head": "Chuveiro",
  "shrink": "Encolher",
  "shrub": "Arbusto",
  "shuffle": "Aleatório",
  "sigma": "Somatório",
  "signal": "Sinal",
  "signal-high": "Sinal alto",
  "signal-low": "Sinal baixo",
  "signal-medium": "Sinal médio",
  "signal-zero": "Sem sinal",
  "signature": "Assinatura",
  "signpost": "Placa de direção",
  "signpost-big": "Placa de direção grande",
  "siren": "Sirene",
  "skip-back": "Voltar faixa",
  "skip-forward": "Avançar faixa",
  "skull": "Caveira",
  "slack": "Slack",
  "slash": "Barra",
  "slice": "Fatiar",
  "sliders-horizontal": "Controles deslizantes (horizontal)",
  "sliders-vertical": "Controles deslizantes (vertical)",
  "smartphone": "Celular",
  "smartphone-charging": "Celular carregando",
  "smartphone-nfc": "Celular com NFC",
  "smile": "Rosto sorrindo",
  "smile-plus": "Rosto sorrindo com mais",
  "snail": "Caracol",
  "snowflake": "Floco de neve",
  "sofa": "Sofá",
  "soup": "Sopa",
  "space": "Espaço (tecla)",
  "spade": "Espadas (naipe)",
  "sparkle": "Brilho simples",
  "sparkles": "Brilho",
  "speaker": "Caixa de som",
  "speech": "Fala",
  "spell-check": "Corretor ortográfico",
  "spell-check-2": "Corretor ortográfico 2",
  "spline": "Curva",
  "split": "Dividir caminho",
  "spray-can": "Lata de spray",
  "sprout": "Broto",
  "square": "Quadrado",
  "square-activity": "Quadrado com atividade",
  "square-arrow-down": "Quadrado com seta para baixo",
  "square-arrow-down-left": "Quadrado com seta (baixo, esquerda)",
  "square-arrow-down-right": "Quadrado com seta (baixo, direita)",
  "square-arrow-left": "Quadrado com seta para a esquerda",
  "square-arrow-out-down-left": "Seta saindo do quadrado (baixo, esquerda)",
  "square-arrow-out-down-right": "Seta saindo do quadrado (baixo, direita)",
  "square-arrow-out-up-left": "Seta saindo do quadrado (cima, esquerda)",
  "square-arrow-out-up-right": "Seta saindo do quadrado (cima, direita)",
  "square-arrow-right": "Quadrado com seta para a direita",
  "square-arrow-up": "Quadrado com seta para cima",
  "square-arrow-up-left": "Quadrado com seta (cima, esquerda)",
  "square-arrow-up-right": "Quadrado com seta (cima, direita)",
  "square-asterisk": "Quadrado com asterisco",
  "square-bottom-dashed-scissors": "Quadrado com tesoura tracejado",
  "square-check": "Quadrado com visto",
  "square-check-big": "Quadrado com visto grande",
  "square-chevron-down": "Quadrado com divisa para baixo",
  "square-chevron-left": "Quadrado com divisa para a esquerda",
  "square-chevron-right": "Quadrado com divisa para a direita",
  "square-chevron-up": "Quadrado com divisa para cima",
  "square-code": "Quadrado com código",
  "square-dashed-bottom": "Quadrado com base tracejada",
  "square-dashed-bottom-code": "Quadrado tracejado com código",
  "square-dashed-kanban": "Kanban tracejado",
  "square-dashed-mouse-pointer": "Quadrado tracejado com ponteiro",
  "square-divide": "Quadrado com divisão",
  "square-dot": "Quadrado com ponto",
  "square-equal": "Quadrado com igual",
  "square-function": "Quadrado com função",
  "square-gantt-chart": "Quadrado com gráfico de Gantt",
  "square-kanban": "Quadrado com kanban",
  "square-library": "Quadrado com biblioteca",
  "square-m": "Quadrado com M",
  "square-menu": "Quadrado com menu",
  "square-minus": "Quadrado com menos",
  "square-mouse-pointer": "Quadrado com ponteiro",
  "square-parking": "Estacionamento (quadrado)",
  "square-parking-off": "Estacionamento proibido (quadrado)",
  "square-pen": "Quadrado com caneta",
  "square-percent": "Quadrado com porcentagem",
  "square-pi": "Quadrado com pi",
  "square-pilcrow": "Quadrado com parágrafo",
  "square-play": "Quadrado com play",
  "square-plus": "Quadrado com mais",
  "square-power": "Quadrado com liga/desliga",
  "square-radical": "Quadrado com raiz",
  "square-scissors": "Quadrado com tesoura",
  "square-sigma": "Quadrado com somatório",
  "square-slash": "Quadrado cortado",
  "square-split-horizontal": "Quadrado dividido na horizontal",
  "square-split-vertical": "Quadrado dividido na vertical",
  "square-stack": "Quadrados empilhados",
  "square-terminal": "Quadrado com terminal",
  "square-user": "Quadrado com usuário",
  "square-user-round": "Quadrado com usuário (arredondado)",
  "square-x": "Quadrado com X",
  "squircle": "Quadrado arredondado",
  "squirrel": "Esquilo",
  "stack-2": "Camadas",
  "stamp": "Carimbo",
  "star": "Estrela",
  "star-half": "Meia estrela",
  "star-off": "Estrela cortada",
  "step-back": "Passo para trás",
  "step-forward": "Passo à frente",
  "stethoscope": "Estetoscópio",
  "sticker": "Adesivo",
  "sticky-note": "Nota adesiva",
  "store": "Loja",
  "stretch-horizontal": "Esticar na horizontal",
  "stretch-vertical": "Esticar na vertical",
  "strikethrough": "Tachado",
  "subscript": "Subscrito",
  "sun": "Sol",
  "sun-dim": "Sol fraco",
  "sun-medium": "Sol médio",
  "sun-moon": "Sol e lua",
  "sun-snow": "Sol e neve",
  "sunrise": "Nascer do sol",
  "sunset": "Pôr do sol",
  "superscript": "Sobrescrito",
  "swatch-book": "Catálogo de cores",
  "swiss-franc": "Franco suíço",
  "switch-camera": "Trocar câmera",
  "sword": "Espada",
  "swords": "Espadas cruzadas",
  "syringe": "Seringa",
  "table": "Tabela",
  "table-2": "Tabela 2",
  "table-cells-merge": "Mesclar células",
  "table-cells-split": "Dividir células",
  "table-columns-split": "Dividir colunas",
  "table-properties": "Propriedades da tabela",
  "table-rows-split": "Dividir linhas",
  "tablet": "Tablet",
  "tablet-smartphone": "Tablet e celular",
  "tablets": "Comprimidos",
  "tag": "Etiqueta",
  "tags": "Etiquetas",
  "tally-1": "Contagem 1",
  "tally-2": "Contagem 2",
  "tally-3": "Contagem 3",
  "tally-4": "Contagem 4",
  "tally-5": "Contagem 5",
  "tangent": "Tangente",
  "target": "Alvo",
  "telescope": "Telescópio",
  "tent": "Barraca",
  "tent-tree": "Barraca e árvore",
  "terminal": "Terminal",
  "test-tube": "Tubo de ensaio",
  "test-tube-diagonal": "Tubo de ensaio (diagonal)",
  "test-tubes": "Tubos de ensaio",
  "text": "Texto",
  "text-cursor": "Cursor de texto",
  "text-cursor-input": "Campo de texto",
  "text-quote": "Citação em texto",
  "text-search": "Buscar no texto",
  "text-select": "Selecionar texto",
  "theater": "Teatro",
  "thermometer": "Termômetro",
  "thermometer-snowflake": "Termômetro frio",
  "thermometer-sun": "Termômetro quente",
  "thumbs-down": "Polegar para baixo",
  "thumbs-up": "Polegar para cima",
  "ticket": "Ingresso",
  "ticket-check": "Ingresso com visto",
  "ticket-minus": "Ingresso com menos",
  "ticket-percent": "Ingresso com desconto",
  "ticket-plus": "Ingresso com mais",
  "ticket-slash": "Ingresso cortado",
  "ticket-x": "Ingresso com X",
  "timer": "Cronômetro",
  "timer-off": "Cronômetro desligado",
  "timer-reset": "Reiniciar cronômetro",
  "toggle-left": "Chave desligada",
  "toggle-right": "Chave ligada",
  "tornado": "Tornado",
  "torus": "Toro",
  "touchpad": "Touchpad",
  "touchpad-off": "Touchpad desligado",
  "tower-control": "Torre de controle",
  "toy-brick": "Bloco de montar",
  "tractor": "Trator",
  "traffic-cone": "Cone de trânsito",
  "train-front": "Trem de frente",
  "train-front-tunnel": "Trem no túnel",
  "train-track": "Trilho de trem",
  "tram-front": "Bonde",
  "trash": "Lixeira",
  "trash-2": "Lixeira 2",
  "tree-deciduous": "Árvore",
  "tree-palm": "Palmeira",
  "tree-pine": "Pinheiro",
  "trees": "Árvores",
  "trello": "Trello",
  "trending-down": "Queda",
  "trending-up": "Crescimento",
  "triangle": "Triângulo",
  "triangle-alert": "Triângulo com alerta",
  "triangle-right": "Triângulo à direita",
  "trophy": "Troféu",
  "truck": "Caminhão",
  "turtle": "Tartaruga",
  "tv": "Televisão",
  "tv-minimal": "TV simples",
  "tv-minimal-play": "TV com play",
  "twitch": "Twitch",
  "twitter": "Twitter",
  "type": "Letra",
  "type-outline": "Letra contornada",
  "umbrella": "Guarda-chuva",
  "umbrella-off": "Guarda-chuva cortado",
  "underline": "Sublinhado",
  "undo": "Desfazer",
  "undo-2": "Desfazer 2",
  "undo-dot": "Desfazer com ponto",
  "unfold-horizontal": "Expandir na horizontal",
  "unfold-vertical": "Expandir na vertical",
  "ungroup": "Desagrupar",
  "university": "Universidade",
  "unlink": "Desvincular",
  "unlink-2": "Desvincular 2",
  "unplug": "Desconectar",
  "upload": "Enviar arquivo",
  "usb": "USB",
  "user": "Usuário",
  "user-check": "Usuário com visto",
  "user-cog": "Usuário com engrenagem",
  "user-minus": "Usuário com menos",
  "user-pen": "Usuário com caneta",
  "user-plus": "Usuário com mais",
  "user-round": "Usuário (arredondado)",
  "user-round-check": "Usuário (arredondado) com visto",
  "user-round-cog": "Usuário (arredondado) com engrenagem",
  "user-round-minus": "Usuário (arredondado) com menos",
  "user-round-pen": "Usuário (arredondado) com caneta",
  "user-round-plus": "Usuário (arredondado) com mais",
  "user-round-search": "Usuário (arredondado) com lupa",
  "user-round-x": "Usuário (arredondado) com X",
  "user-search": "Usuário com lupa",
  "user-x": "Usuário com X",
  "users": "Pessoas",
  "users-round": "Pessoas (arredondado)",
  "utensils": "Talheres",
  "utensils-crossed": "Talheres cruzados",
  "utility-pole": "Poste",
  "variable": "Variável",
  "vault": "Cofre",
  "vegan": "Vegano",
  "venetian-mask": "Máscara veneziana",
  "vibrate": "Vibrar",
  "vibrate-off": "Vibrar desligado",
  "video": "Vídeo",
  "video-off": "Vídeo desligado",
  "videotape": "Fita de vídeo",
  "view": "Visualizar",
  "voicemail": "Correio de voz",
  "volume": "Volume",
  "volume-1": "Volume baixo",
  "volume-2": "Volume alto",
  "volume-x": "Mudo",
  "vote": "Votar",
  "wallet": "Carteira",
  "wallet-cards": "Carteira com cartões",
  "wallet-minimal": "Carteira simples",
  "wallpaper": "Papel de parede",
  "wand": "Varinha mágica",
  "wand-sparkles": "Varinha com brilho",
  "warehouse": "Armazém",
  "washing-machine": "Máquina de lavar",
  "watch": "Relógio de pulso",
  "waves": "Ondas",
  "waypoints": "Pontos de rota",
  "webcam": "Webcam",
  "webhook": "Webhook",
  "webhook-off": "Webhook desligado",
  "weight": "Peso",
  "wheat": "Trigo",
  "wheat-off": "Trigo cortado",
  "whole-word": "Palavra inteira",
  "wifi": "Wi-Fi",
  "wifi-high": "Wi-Fi forte",
  "wifi-low": "Wi-Fi fraco",
  "wifi-off": "Wi-Fi desligado",
  "wifi-zero": "Wi-Fi sem sinal",
  "wind": "Vento",
  "wine": "Vinho",
  "wine-off": "Vinho cortado",
  "workflow": "Fluxo de trabalho",
  "worm": "Minhoca",
  "wrap-text": "Quebrar texto",
  "wrench": "Chave inglesa",
  "x": "X",
  "youtube": "YouTube",
  "zap": "Raio (Lucide)",
  "zap-off": "Raio cortado",
  "zoom-in": "Aproximar",
  "zoom-out": "Afastar",
};

/** Palavras a mais que a busca aceita (a busca também lê o nome em inglês). */
export const SINONIMOS_DO_ICONE: Record<string, string> = {
  "a-arrow-down": "diminuir fonte texto",
  "a-arrow-up": "aumentar fonte texto",
  "a-large-small": "fonte texto",
  "accessibility": "inclusão deficiência",
  "activity": "batimento pulso",
  "air-vent": "ar condicionado ventilação",
  "airplay": "transmitir",
  "alarm-clock": "alarme hora",
  "alarm-clock-check": "alarme",
  "alarm-clock-minus": "alarme",
  "alarm-clock-off": "alarme",
  "alarm-clock-plus": "alarme",
  "alarm-smoke": "alarme incêndio",
  "album": "disco música",
  "align-center": "alinhar",
  "align-horizontal-distribute-center": "alinhar",
  "align-horizontal-distribute-end": "alinhar",
  "align-horizontal-distribute-start": "alinhar",
  "align-horizontal-justify-center": "alinhar",
  "align-horizontal-justify-end": "alinhar",
  "align-horizontal-justify-start": "alinhar",
  "align-horizontal-space-around": "alinhar",
  "align-horizontal-space-between": "alinhar",
  "align-justify": "alinhar",
  "align-left": "alinhar",
  "align-right": "alinhar",
  "align-vertical-distribute-center": "alinhar",
  "align-vertical-distribute-end": "alinhar",
  "align-vertical-distribute-start": "alinhar",
  "align-vertical-justify-center": "alinhar",
  "align-vertical-justify-end": "alinhar",
  "align-vertical-justify-start": "alinhar",
  "align-vertical-space-around": "alinhar",
  "align-vertical-space-between": "alinhar",
  "ambulance": "saúde emergência hospital",
  "ampersand": "símbolo",
  "ampersands": "símbolo",
  "anchor": "navio mar",
  "angry": "raiva emoji",
  "annoyed": "emoji",
  "antenna": "sinal",
  "anvil": "ferreiro",
  "aperture": "foto lente",
  "app-window": "programa",
  "app-window-mac": "programa",
  "apple": "fruta",
  "archive": "caixa guardar",
  "archive-restore": "caixa",
  "archive-x": "caixa excluir",
  "area-chart": "dados análise",
  "armchair": "sofá móvel",
  "arrow-down-0-1": "crescente classificar",
  "arrow-down-1-0": "decrescente classificar",
  "arrow-down-a-z": "alfabética classificar",
  "arrow-down-left": "diagonal",
  "arrow-down-narrow-wide": "classificar",
  "arrow-down-right": "diagonal",
  "arrow-down-to-line": "baixar",
  "arrow-down-up": "trocar ordenar",
  "arrow-down-wide-narrow": "classificar",
  "arrow-down-z-a": "alfabética classificar",
  "arrow-left": "voltar",
  "arrow-left-right": "trocar",
  "arrow-right": "avançar próximo",
  "arrow-right-left": "trocar",
  "arrow-up": "subir",
  "arrow-up-0-1": "classificar",
  "arrow-up-1-0": "classificar",
  "arrow-up-a-z": "alfabética classificar",
  "arrow-up-down": "trocar ordenar",
  "arrow-up-from-line": "subir enviar",
  "arrow-up-left": "diagonal",
  "arrow-up-narrow-wide": "classificar",
  "arrow-up-right": "diagonal link externo",
  "arrow-up-wide-narrow": "classificar",
  "arrow-up-z-a": "alfabética classificar",
  "asterisk": "estrela símbolo",
  "at-sign": "email símbolo",
  "atom": "ciência física",
  "audio-lines": "som onda voz",
  "audio-waveform": "som voz",
  "award": "medalha conquista certificado",
  "axe": "ferramenta",
  "axis-3d": "coordenadas",
  "baby": "criança",
  "backpack": "escola estudante",
  "badge": "distintivo emblema",
  "badge-cent": "dinheiro preço",
  "badge-check": "verificado aprovado certificado",
  "badge-dollar-sign": "dinheiro preço",
  "badge-euro": "dinheiro preço",
  "badge-help": "ajuda dúvida",
  "badge-indian-rupee": "dinheiro preço",
  "badge-japanese-yen": "dinheiro preço",
  "badge-percent": "desconto promoção",
  "badge-pound-sterling": "dinheiro preço",
  "badge-russian-ruble": "dinheiro preço",
  "badge-swiss-franc": "dinheiro preço",
  "baggage-claim": "mala aeroporto viagem",
  "ban": "bloqueado cancelar",
  "banana": "fruta",
  "banknote": "dinheiro nota pagamento",
  "bar-chart": "dados análise bi",
  "bar-chart-2": "dados análise",
  "bar-chart-3": "dados análise",
  "bar-chart-4": "dados análise",
  "bar-chart-big": "dados análise",
  "bar-chart-horizontal": "dados análise",
  "bar-chart-horizontal-big": "dados análise",
  "barcode": "produto",
  "baseline": "texto fonte",
  "bath": "banho",
  "battery": "energia",
  "battery-charging": "energia",
  "battery-full": "energia",
  "battery-low": "energia",
  "battery-medium": "energia",
  "battery-warning": "energia",
  "beaker": "ciência laboratório química",
  "bean": "feijão café",
  "bean-off": "feijão café",
  "bed": "quarto dormir",
  "bed-double": "quarto",
  "bed-single": "quarto",
  "beef": "comida",
  "beer": "bebida chopp",
  "beer-off": "bebida",
  "bell": "notificação aviso",
  "bell-dot": "notificação",
  "bell-electric": "alarme",
  "bell-minus": "notificação",
  "bell-off": "notificação silenciar",
  "bell-plus": "notificação",
  "bell-ring": "notificação alerta",
  "biceps-flexed": "força músculo academia",
  "bike": "ciclismo",
  "binary": "zeros uns computação",
  "biohazard": "perigo",
  "bird": "ave animal",
  "bitcoin": "criptomoeda dinheiro",
  "blend": "misturar cores",
  "blinds": "janela",
  "blocks": "peças montar",
  "bold": "texto fonte",
  "bolt": "rápido energia",
  "bomb": "explosão",
  "bone": "cachorro",
  "book": "leitura estudo",
  "book-a": "dicionário",
  "book-audio": "livro som",
  "book-check": "leitura concluída",
  "book-dashed": "rascunho",
  "book-down": "baixar",
  "book-headphones": "audiolivro",
  "book-heart": "favorito",
  "book-image": "ilustrado",
  "book-lock": "protegido",
  "book-marked": "marcador",
  "book-open": "leitura estudo aula",
  "book-open-check": "leitura concluída",
  "book-open-text": "leitura estudo",
  "book-type": "tipografia",
  "book-user": "biografia contatos",
  "bookmark": "salvar favorito",
  "bookmark-check": "salvo",
  "bookmark-plus": "salvar",
  "boom-box": "rádio música",
  "bot": "ia chatbot assistente",
  "bot-message-square": "chatbot ia assistente",
  "bot-off": "ia",
  "box": "pacote produto",
  "boxes": "pacotes estoque",
  "braces": "programação json",
  "brackets": "programação código",
  "brain": "mente pensar inteligência",
  "brain-circuit": "ia inteligência artificial",
  "brain-cog": "ia pensamento",
  "brick-wall": "parede construção obra",
  "briefcase": "trabalho carreira emprego",
  "briefcase-business": "trabalho empresa",
  "briefcase-medical": "saúde",
  "bring-to-front": "camada",
  "brush": "pintura arte",
  "bug": "erro bug defeito",
  "bug-off": "sem erro bug",
  "bug-play": "depurar erro bug",
  "building": "empresa escritório",
  "building-2": "empresa escritório",
  "bus": "transporte",
  "bus-front": "transporte",
  "cable": "fio conexão",
  "cable-car": "bondinho",
  "cake": "aniversário festa",
  "cake-slice": "doce aniversário",
  "calculator": "conta matemática",
  "calendar": "data agenda",
  "calendar-arrow-down": "data",
  "calendar-arrow-up": "data",
  "calendar-check": "data agenda",
  "calendar-check-2": "data agenda",
  "calendar-clock": "agenda horário",
  "calendar-cog": "agenda configurar",
  "calendar-days": "data agenda",
  "calendar-fold": "data agenda",
  "calendar-heart": "data especial",
  "calendar-minus": "data",
  "calendar-minus-2": "data",
  "calendar-off": "data",
  "calendar-plus": "agendar",
  "calendar-plus-2": "agendar",
  "calendar-range": "datas intervalo",
  "calendar-search": "buscar data",
  "calendar-x": "cancelar",
  "calendar-x-2": "cancelar",
  "camera": "foto fotografia",
  "camera-off": "foto",
  "candlestick-chart": "bolsa ações finanças",
  "candy": "doce",
  "candy-cane": "natal",
  "candy-off": "doce",
  "cannabis": "folha",
  "captions": "vídeo texto",
  "car": "veículo transporte",
  "car-front": "veículo",
  "car-taxi-front": "carro transporte",
  "caravan": "viagem",
  "carrot": "legume comida",
  "case-lower": "texto",
  "case-sensitive": "texto",
  "case-upper": "texto",
  "cassette-tape": "música",
  "cast": "tela chromecast",
  "castle": "fortaleza",
  "cat": "animal",
  "cctv": "vigilância",
  "check": "certo confirmado ok",
  "check-check": "lido confirmado",
  "chef-hat": "cozinha",
  "cherry": "fruta",
  "chevron-down": "seta",
  "chevron-first": "seta primeiro",
  "chevron-last": "seta último",
  "chevron-left": "seta",
  "chevron-right": "seta",
  "chevron-up": "seta",
  "chevrons-down": "seta",
  "chevrons-down-up": "seta",
  "chevrons-left": "seta",
  "chevrons-left-right": "seta",
  "chevrons-right": "seta",
  "chevrons-right-left": "seta",
  "chevrons-up": "seta",
  "chevrons-up-down": "seta",
  "chrome": "navegador",
  "church": "templo",
  "cigarette": "fumar",
  "cigarette-off": "cigarro",
  "circle": "forma",
  "circle-alert": "atenção aviso",
  "circle-check": "confirmado concluído",
  "circle-check-big": "confirmado concluído",
  "circle-divide": "matemática",
  "circle-dollar-sign": "dinheiro moeda",
  "circle-dot": "alvo",
  "circle-ellipsis": "mais opções",
  "circle-equal": "matemática",
  "circle-gauge": "desempenho",
  "circle-help": "ajuda dúvida pergunta",
  "circle-percent": "desconto",
  "circle-play": "vídeo reproduzir",
  "circle-plus": "adicionar",
  "circle-power": "energia",
  "circle-slash": "proibido",
  "circle-user": "perfil conta pessoa",
  "circle-user-round": "perfil conta pessoa",
  "circle-x": "erro fechar",
  "circuit-board": "eletrônica hardware",
  "citrus": "fruta laranja",
  "clapperboard": "cinema filme vídeo",
  "clipboard-check": "tarefa concluída",
  "clipboard-list": "tarefas checklist",
  "clipboard-pen": "editar formulário",
  "clipboard-pen-line": "editar",
  "clock": "tempo hora duração",
  "clock-1": "hora",
  "clock-10": "hora",
  "clock-11": "hora",
  "clock-12": "hora",
  "clock-2": "hora",
  "clock-3": "hora",
  "clock-4": "hora",
  "clock-5": "hora",
  "clock-6": "hora",
  "clock-7": "hora",
  "clock-8": "hora",
  "clock-9": "hora",
  "clock-arrow-down": "tempo",
  "clock-arrow-up": "tempo",
  "cloud": "computação na nuvem",
  "cloud-cog": "configuração servidor",
  "cloud-download": "baixar",
  "cloud-drizzle": "chuva tempo",
  "cloud-fog": "tempo",
  "cloud-hail": "tempo",
  "cloud-lightning": "raio tempo",
  "cloud-moon": "noite tempo",
  "cloud-moon-rain": "tempo",
  "cloud-off": "offline",
  "cloud-rain": "tempo",
  "cloud-rain-wind": "tempo",
  "cloud-snow": "tempo",
  "cloud-sun": "tempo",
  "cloud-sun-rain": "tempo",
  "cloud-upload": "enviar",
  "cloudy": "tempo",
  "clover": "sorte",
  "club": "baralho cartas",
  "code": "programação",
  "code-xml": "html programação",
  "coffee": "xícara pausa",
  "cog": "configurar",
  "coins": "dinheiro finanças",
  "columns-2": "layout",
  "columns-3": "layout",
  "columns-4": "layout",
  "combine": "juntar",
  "command": "atalho teclado mac",
  "compass": "direção orientação",
  "component": "peças design",
  "computer": "pc desktop",
  "concierge-bell": "atendimento hotel",
  "cone": "forma geometria",
  "construction": "obra placa em obras",
  "contact": "agenda pessoa",
  "contact-round": "agenda pessoa",
  "container": "docker caixa",
  "cookie": "cookie",
  "cooking-pot": "cozinha",
  "copy": "duplicar",
  "copyleft": "licença",
  "copyright": "copyright",
  "corner-down-left": "seta enter",
  "corner-down-right": "seta",
  "corner-left-down": "seta",
  "corner-left-up": "seta",
  "corner-right-down": "seta",
  "corner-right-up": "seta",
  "corner-up-left": "seta",
  "corner-up-right": "seta",
  "cpu": "chip hardware",
  "creative-commons": "licença",
  "credit-card": "pagamento",
  "croissant": "pão café da manhã",
  "crop": "imagem",
  "crosshair": "alvo",
  "crown": "rei premium",
  "cuboid": "forma 3d",
  "cup-soda": "bebida",
  "currency": "dinheiro",
  "cylinder": "forma",
  "database": "dados sql",
  "database-backup": "cópia de segurança",
  "database-zap": "rápido",
  "delete": "excluir",
  "dessert": "doce",
  "diameter": "medida",
  "diamond": "diamante forma",
  "diamond-percent": "desconto",
  "dice-1": "jogo",
  "dice-2": "jogo",
  "dice-3": "jogo",
  "dice-4": "jogo",
  "dice-5": "jogo",
  "dice-6": "jogo",
  "dices": "sorte",
  "diff": "comparar",
  "disc": "cd",
  "disc-2": "cd",
  "disc-3": "cd",
  "disc-album": "música cd",
  "divide": "divisão matemática",
  "dna": "genética biologia",
  "dock": "barra de aplicativos",
  "dog": "animal",
  "dollar-sign": "dinheiro dólar",
  "donut": "gráfico de rosca doce",
  "door-open": "entrada",
  "download": "download",
  "drafting-compass": "desenho técnico geometria",
  "drama": "drama",
  "drill": "ferramenta obra",
  "droplet": "água",
  "droplets": "água",
  "drum": "música bateria",
  "drumstick": "comida",
  "dumbbell": "academia exercício",
  "ear": "ouvir",
  "ear-off": "surdo",
  "earth": "mundo global",
  "earth-lock": "segurança global",
  "egg-fried": "comida",
  "ellipsis": "mais opções",
  "ellipsis-vertical": "mais opções menu",
  "equal": "matemática",
  "equal-not": "matemática",
  "eraser": "apagar",
  "euro": "dinheiro moeda",
  "expand": "tela cheia ampliar",
  "external-link": "abrir fora",
  "eye": "ver visualizar",
  "eye-off": "ocultar esconder",
  "facebook": "rede social",
  "factory": "indústria produção",
  "feather": "escrita leve",
  "ferris-wheel": "parque",
  "figma": "design",
  "file": "documento página",
  "file-archive": "zip documento",
  "file-audio": "documento som",
  "file-audio-2": "documento som",
  "file-axis-3d": "documento",
  "file-badge": "documento certificado",
  "file-badge-2": "documento certificado",
  "file-bar-chart": "relatório documento",
  "file-bar-chart-2": "relatório documento",
  "file-box": "documento pacote",
  "file-check": "documento aprovado",
  "file-check-2": "documento aprovado",
  "file-clock": "documento histórico",
  "file-code": "documento programação",
  "file-code-2": "documento programação",
  "file-cog": "documento configuração",
  "file-diff": "documento comparar",
  "file-digit": "documento binário",
  "file-down": "documento baixar",
  "file-heart": "documento favorito",
  "file-image": "documento foto",
  "file-input": "documento importar",
  "file-json": "documento dados",
  "file-json-2": "documento dados",
  "file-key": "documento",
  "file-key-2": "documento",
  "file-line-chart": "relatório documento",
  "file-lock": "documento protegido",
  "file-lock-2": "documento protegido",
  "file-minus": "documento",
  "file-minus-2": "documento",
  "file-music": "documento som",
  "file-output": "documento exportar",
  "file-pen": "documento editar",
  "file-pen-line": "documento editar",
  "file-pie-chart": "relatório documento",
  "file-plus": "documento novo",
  "file-plus-2": "documento novo",
  "file-question": "documento dúvida",
  "file-scan": "documento",
  "file-search": "documento buscar",
  "file-search-2": "documento buscar",
  "file-sliders": "documento ajustes",
  "file-spreadsheet": "arquivo excel tabela documento",
  "file-stack": "documentos",
  "file-symlink": "documento link",
  "file-terminal": "documento script",
  "file-text": "arquivo texto",
  "file-type": "documento fonte",
  "file-type-2": "documento fonte",
  "file-up": "documento enviar",
  "file-video": "documento filme",
  "file-video-2": "documento filme",
  "file-volume": "documento áudio",
  "file-volume-2": "documento áudio",
  "file-warning": "documento",
  "file-x": "documento",
  "file-x-2": "documento",
  "files": "documentos",
  "film": "cinema vídeo",
  "filter": "funil",
  "filter-x": "limpar filtro",
  "fingerprint": "segurança identidade",
  "fire-extinguisher": "incêndio segurança",
  "fish": "animal",
  "flag": "meta objetivo",
  "flag-triangle-right": "meta",
  "flame": "fogo quente",
  "flame-kindling": "fogo",
  "flashlight": "luz",
  "flask-conical": "laboratório química ciência",
  "flask-round": "laboratório química ciência",
  "flip-horizontal": "inverter",
  "flip-horizontal-2": "inverter",
  "flip-vertical": "inverter",
  "flip-vertical-2": "inverter",
  "flower": "planta",
  "flower-2": "planta",
  "focus": "mira concentração",
  "folder": "diretório",
  "folder-archive": "zip",
  "folder-clock": "histórico",
  "folder-code": "projeto programação",
  "folder-cog": "configuração",
  "folder-down": "baixar",
  "folder-git": "repositório",
  "folder-git-2": "repositório",
  "folder-heart": "favoritos",
  "folder-input": "importar",
  "folder-kanban": "projeto",
  "folder-lock": "protegida",
  "folder-output": "exportar",
  "folder-pen": "renomear",
  "folder-plus": "nova pasta",
  "folder-search": "buscar",
  "folder-search-2": "buscar",
  "folder-symlink": "link",
  "folder-tree": "estrutura hierarquia",
  "folder-up": "enviar",
  "folders": "diretórios",
  "footprints": "passos caminho jornada",
  "forklift": "logística armazém",
  "forward": "seta",
  "frame": "quadro",
  "framer": "design",
  "frown": "emoji",
  "fuel": "posto gasolina",
  "fullscreen": "expandir",
  "gallery-horizontal": "imagens carrossel",
  "gallery-horizontal-end": "imagens",
  "gallery-thumbnails": "imagens",
  "gallery-vertical": "imagens",
  "gallery-vertical-end": "imagens",
  "gamepad": "jogo game",
  "gamepad-2": "jogo",
  "gantt-chart": "cronograma projeto",
  "gauge": "medidor desempenho",
  "gavel": "lei justiça leilão",
  "gem": "diamante valor premium",
  "gift": "bônus brinde",
  "git-branch": "git versão",
  "git-commit-horizontal": "versão",
  "git-commit-vertical": "versão",
  "git-fork": "bifurcação",
  "git-graph": "histórico",
  "git-merge": "juntar",
  "git-pull-request": "git",
  "glass-water": "bebida",
  "glasses": "ler visão",
  "globe": "mundo internet idioma",
  "globe-lock": "segurança internet",
  "goal": "meta objetivo",
  "grab": "arrastar",
  "graduation-cap": "formatura diploma educação curso",
  "grape": "fruta",
  "grid-2x2": "tabela",
  "grid-3x3": "tabela",
  "grip": "arrastar",
  "grip-horizontal": "arrastar",
  "grip-vertical": "arrastar",
  "guitar": "música guitarra",
  "ham": "comida",
  "hammer": "ferramenta construção obra",
  "hand": "parar",
  "hand-coins": "pagamento dinheiro",
  "hand-heart": "doação cuidado",
  "hand-helping": "ajuda apoio",
  "hand-platter": "servir",
  "handshake": "acordo parceria negócio",
  "hard-drive": "hd armazenamento",
  "hard-hat": "construção segurança",
  "hash": "hashtag número",
  "haze": "tempo",
  "hdmi-port": "cabo",
  "heading": "cabeçalho texto",
  "heading-1": "cabeçalho texto",
  "heading-2": "cabeçalho texto",
  "heading-3": "cabeçalho texto",
  "heading-4": "cabeçalho texto",
  "heading-5": "cabeçalho texto",
  "heading-6": "cabeçalho texto",
  "headphones": "áudio música",
  "headset": "fone microfone suporte atendimento",
  "heart": "amor favorito curtir",
  "heart-handshake": "parceria cuidado",
  "heart-pulse": "saúde",
  "hexagon": "forma",
  "highlighter": "destacar",
  "history": "tempo voltar",
  "hop": "cerveja",
  "hospital": "saúde",
  "hotel": "hospedagem",
  "hourglass": "tempo espera",
  "house": "início lar",
  "house-plug": "energia",
  "ice-cream-bowl": "doce",
  "ice-cream-cone": "doce",
  "image": "foto figura",
  "image-down": "foto",
  "image-minus": "foto",
  "image-off": "foto",
  "image-play": "vídeo foto",
  "image-plus": "foto adicionar",
  "image-up": "foto enviar",
  "images": "fotos galeria",
  "import": "entrada",
  "inbox": "email mensagens",
  "indent-decrease": "texto",
  "indent-increase": "texto",
  "indian-rupee": "dinheiro moeda",
  "infinity": "ilimitado",
  "instagram": "rede social",
  "italic": "texto fonte",
  "iteration-ccw": "repetir ciclo",
  "iteration-cw": "repetir ciclo",
  "japanese-yen": "dinheiro moeda",
  "joystick": "jogo",
  "kanban": "quadro tarefas projeto",
  "key": "senha acesso",
  "key-round": "senha acesso",
  "key-square": "senha acesso",
  "keyboard": "digitar",
  "keyboard-music": "piano",
  "lamp": "luz",
  "lamp-ceiling": "luz",
  "lamp-desk": "luz estudo",
  "lamp-floor": "luz",
  "lamp-wall-down": "luz",
  "lamp-wall-up": "luz",
  "land-plot": "lote",
  "landmark": "banco governo museu",
  "languages": "tradução língua",
  "laptop": "computador",
  "laptop-minimal": "computador",
  "lasso": "selecionar",
  "laugh": "emoji feliz",
  "layers": "pilha",
  "layers-3": "camadas",
  "layout-dashboard": "dashboard bi",
  "layout-template": "template",
  "leaf": "planta natureza",
  "leafy-green": "alface salada",
  "lectern": "palestra discurso",
  "library": "livros estante",
  "library-big": "livros",
  "life-buoy": "ajuda suporte",
  "ligature": "fonte texto",
  "lightbulb": "ideia dica",
  "line-chart": "dados tendência",
  "link": "corrente ligação",
  "link-2": "corrente",
  "linkedin": "rede social carreira",
  "list-check": "tarefas",
  "list-checks": "lista tarefas",
  "list-filter": "filtro",
  "list-music": "playlist",
  "list-todo": "afazeres",
  "list-tree": "hierarquia",
  "list-video": "playlist aulas",
  "locate": "gps mira",
  "locate-fixed": "gps",
  "locate-off": "gps",
  "lock": "segurança bloqueado senha",
  "lock-keyhole": "segurança",
  "lock-keyhole-open": "desbloqueado",
  "lock-open": "desbloqueado",
  "log-in": "login",
  "log-out": "logout",
  "logs": "logs",
  "lollipop": "doce",
  "luggage": "viagem bagagem",
  "magnet": "atração",
  "mail": "carta envelope mensagem",
  "mail-check": "carta",
  "mail-minus": "carta",
  "mail-open": "carta",
  "mail-plus": "carta",
  "mail-question": "carta",
  "mail-search": "carta",
  "mail-warning": "carta",
  "mail-x": "carta",
  "mailbox": "carta",
  "mails": "cartas",
  "map": "trilha caminho",
  "map-pin": "local endereço pino",
  "map-pinned": "local",
  "martini": "drinque bebida",
  "medal": "prêmio conquista",
  "megaphone": "anúncio marketing aviso",
  "meh": "emoji",
  "memory-stick": "hardware",
  "menu": "hambúrguer",
  "merge": "mesclar",
  "message-circle": "mensagem chat comentário",
  "message-circle-code": "mensagem chat",
  "message-circle-dashed": "mensagem chat",
  "message-circle-heart": "mensagem chat",
  "message-circle-more": "mensagem chat digitando",
  "message-circle-off": "mensagem chat",
  "message-circle-plus": "mensagem chat",
  "message-circle-question": "mensagem chat dúvida pergunta",
  "message-circle-reply": "mensagem chat",
  "message-circle-warning": "mensagem chat",
  "message-circle-x": "mensagem chat",
  "message-square": "chat comentário",
  "message-square-code": "chat",
  "message-square-dashed": "chat",
  "message-square-diff": "chat",
  "message-square-dot": "chat nova",
  "message-square-heart": "chat",
  "message-square-more": "chat",
  "message-square-off": "chat",
  "message-square-plus": "chat",
  "message-square-quote": "chat depoimento",
  "message-square-reply": "chat",
  "message-square-share": "chat",
  "message-square-text": "chat comentário",
  "message-square-warning": "chat",
  "message-square-x": "chat",
  "messages-square": "chat conversa comunidade",
  "mic": "voz gravar áudio",
  "mic-off": "mudo",
  "mic-vocal": "cantar voz",
  "microscope": "ciência laboratório",
  "microwave": "cozinha",
  "milestone": "etapa placa caminho",
  "milk": "bebida",
  "minus": "subtrair",
  "monitor": "tela computador",
  "monitor-check": "tela",
  "monitor-cog": "tela configuração",
  "monitor-dot": "tela",
  "monitor-down": "tela baixar",
  "monitor-off": "tela",
  "monitor-pause": "tela",
  "monitor-play": "tela vídeo aula",
  "monitor-smartphone": "responsivo",
  "monitor-stop": "tela",
  "monitor-up": "tela enviar",
  "monitor-x": "tela",
  "moon": "noite modo escuro",
  "moon-star": "noite",
  "mountain": "desafio",
  "mouse-pointer": "cursor",
  "mouse-pointer-2": "cursor",
  "mouse-pointer-ban": "cursor",
  "mouse-pointer-click": "cursor",
  "move": "arrastar",
  "music": "nota musical",
  "music-2": "música",
  "music-3": "música",
  "music-4": "música",
  "navigation": "seta gps",
  "navigation-2": "seta gps",
  "network": "conexões nós",
  "newspaper": "notícias",
  "nfc": "pagamento aproximação",
  "notebook": "anotações estudo",
  "notebook-pen": "anotações estudo",
  "notebook-tabs": "anotações",
  "notebook-text": "anotações estudo",
  "notepad-text": "anotações",
  "notepad-text-dashed": "rascunho",
  "nut": "castanha",
  "octagon": "pare forma",
  "octagon-alert": "pare",
  "octagon-x": "pare",
  "option": "mac teclado",
  "orbit": "planeta espaço",
  "origami": "papel dobradura",
  "package": "caixa encomenda produto entrega",
  "package-2": "caixa encomenda",
  "package-check": "caixa entregue",
  "package-minus": "caixa",
  "package-open": "caixa",
  "package-plus": "caixa",
  "package-search": "caixa rastrear",
  "package-x": "caixa",
  "paint-bucket": "pintura",
  "paint-roller": "obra parede",
  "paintbrush": "pintura arte",
  "paintbrush-vertical": "pintura arte",
  "palette": "arte design",
  "panel-left": "barra lateral",
  "panel-left-close": "barra lateral",
  "panel-left-open": "barra lateral",
  "panels-left-bottom": "layout",
  "panels-right-bottom": "layout",
  "panels-top-left": "layout",
  "paperclip": "anexo",
  "parentheses": "código matemática",
  "parking-meter": "estacionamento",
  "party-popper": "festa comemoração parabéns",
  "paw-print": "pata pet",
  "pc-case": "pc",
  "pen": "editar escrever",
  "pen-line": "editar escrever",
  "pen-tool": "desenho vetor design",
  "pencil": "editar escrever",
  "pencil-line": "editar escrever",
  "pencil-ruler": "desenho projeto",
  "pentagon": "forma",
  "percent": "desconto",
  "person-standing": "usuário boneco",
  "philippine-peso": "dinheiro moeda",
  "phone": "ligação contato",
  "phone-call": "ligação",
  "phone-forwarded": "telefone",
  "phone-incoming": "telefone",
  "phone-missed": "telefone",
  "phone-outgoing": "telefone",
  "pi": "matemática",
  "piano": "música",
  "pickaxe": "mineração ferramenta obra",
  "picture-in-picture": "vídeo",
  "picture-in-picture-2": "vídeo",
  "pie-chart": "dados análise",
  "piggy-bank": "economia poupança dinheiro",
  "pilcrow": "texto",
  "pilcrow-left": "texto",
  "pilcrow-right": "texto",
  "pill": "remédio saúde",
  "pill-bottle": "saúde",
  "pin": "fixar",
  "pipette": "conta-gotas cor",
  "pizza": "comida",
  "plane": "viagem",
  "plane-landing": "viagem",
  "plane-takeoff": "viagem lançamento",
  "play": "reproduzir vídeo",
  "plug": "tomada integração",
  "plug-2": "plugue",
  "plug-zap": "energia",
  "plus": "adicionar",
  "pocket": "bolso",
  "pocket-knife": "ferramenta",
  "podcast": "áudio",
  "pointer": "cursor clique",
  "popcorn": "cinema",
  "popsicle": "sorvete",
  "pound-sterling": "dinheiro moeda",
  "power": "energia",
  "power-off": "energia",
  "presentation": "aula slide palestra",
  "printer": "imprimir",
  "projector": "apresentação",
  "proportions": "tamanho",
  "puzzle": "peça solução",
  "pyramid": "forma",
  "qr-code": "código",
  "quote": "citação depoimento",
  "rabbit": "rápido animal",
  "radiation": "perigo",
  "radical": "matemática",
  "radio": "transmissão ao vivo",
  "radio-tower": "transmissão sinal",
  "radius": "círculo",
  "rail-symbol": "ferrovia",
  "rat": "animal",
  "ratio": "tela",
  "receipt": "nota fiscal compra pagamento",
  "receipt-cent": "nota fiscal",
  "receipt-euro": "nota fiscal",
  "receipt-indian-rupee": "nota fiscal",
  "receipt-japanese-yen": "nota fiscal",
  "receipt-pound-sterling": "nota fiscal",
  "receipt-russian-ruble": "nota fiscal",
  "receipt-swiss-franc": "nota fiscal",
  "receipt-text": "nota fiscal",
  "rectangle-ellipsis": "campo senha",
  "rectangle-horizontal": "forma",
  "rectangle-vertical": "forma",
  "recycle": "reciclagem sustentabilidade",
  "refresh-ccw": "recarregar",
  "refresh-cw": "recarregar",
  "refrigerator": "cozinha",
  "regex": "regex código",
  "remove-formatting": "texto",
  "repeat": "ciclo loop",
  "replace": "trocar",
  "rewind": "retroceder",
  "ribbon": "conscientização",
  "rocket": "lançamento crescimento",
  "roller-coaster": "parque",
  "route": "caminho trajeto trilha jornada",
  "router": "internet wi-fi",
  "rows-2": "layout",
  "rows-3": "layout",
  "rows-4": "layout",
  "rss": "feed",
  "ruler": "medida",
  "russian-ruble": "dinheiro moeda",
  "sailboat": "barco",
  "salad": "comida",
  "sandwich": "comida",
  "satellite": "espaço",
  "save": "disquete",
  "save-all": "disquete",
  "save-off": "disquete",
  "scale": "justiça equilíbrio",
  "scaling": "escala",
  "scan-face": "rosto",
  "scatter-chart": "dados análise",
  "school": "educação ensino",
  "scissors": "recortar cortar",
  "scissors-line-dashed": "recortar",
  "scroll": "diploma",
  "search": "buscar pesquisa",
  "search-check": "buscar",
  "search-code": "buscar",
  "search-slash": "buscar",
  "search-x": "buscar",
  "section": "seção",
  "send": "avião de papel mensagem",
  "send-horizontal": "mensagem",
  "send-to-back": "camada",
  "server": "backend",
  "settings": "configurações",
  "settings-2": "configurações controles",
  "shapes": "geometria",
  "sheet": "tabela",
  "shield": "segurança proteção",
  "shield-alert": "segurança",
  "shield-ban": "segurança",
  "shield-check": "segurança protegido",
  "shield-ellipsis": "segurança",
  "shield-half": "segurança",
  "shield-minus": "segurança",
  "shield-off": "segurança",
  "shield-plus": "segurança",
  "shield-question": "segurança",
  "shield-x": "segurança",
  "ship": "barco",
  "ship-wheel": "navio direção",
  "shirt": "roupa",
  "shopping-bag": "loja",
  "shopping-basket": "loja mercado",
  "shopping-cart": "loja",
  "shovel": "obra ferramenta",
  "shower-head": "banho",
  "shrub": "planta",
  "shuffle": "embaralhar",
  "sigma": "soma matemática",
  "signpost": "caminho",
  "signpost-big": "caminho",
  "siren": "alerta emergência",
  "skip-back": "anterior",
  "skip-forward": "próximo",
  "sliders-horizontal": "ajustes filtro",
  "sliders-vertical": "ajustes",
  "smartphone": "smartphone telefone",
  "smartphone-nfc": "pagamento",
  "smile": "feliz emoji",
  "smile-plus": "reação emoji",
  "snail": "lento",
  "snowflake": "frio",
  "soup": "comida",
  "spade": "baralho cartas",
  "sparkles": "ia mágica destaque",
  "speaker": "áudio",
  "speech": "voz",
  "split": "bifurcação",
  "spray-can": "tinta grafite",
  "sprout": "crescimento iniciante",
  "square": "forma",
  "square-arrow-out-up-right": "link externo",
  "square-bottom-dashed-scissors": "recortar",
  "square-check": "caixa de seleção",
  "square-check-big": "caixa de seleção",
  "square-function": "matemática fórmula",
  "square-gantt-chart": "cronograma",
  "square-kanban": "tarefas",
  "square-mouse-pointer": "clique",
  "square-pen": "editar",
  "square-play": "vídeo",
  "square-plus": "adicionar",
  "squircle": "forma",
  "squirrel": "animal",
  "star": "favorito avaliação",
  "star-half": "avaliação",
  "stethoscope": "saúde médico",
  "sticky-note": "post-it lembrete",
  "store": "comércio",
  "strikethrough": "texto",
  "subscript": "texto",
  "sun": "dia modo claro",
  "sun-dim": "brilho",
  "sun-medium": "brilho",
  "sun-moon": "dia noite",
  "sunrise": "manhã",
  "sunset": "tarde",
  "superscript": "texto",
  "swatch-book": "design paleta",
  "swiss-franc": "dinheiro moeda",
  "swords": "batalha",
  "syringe": "vacina saúde",
  "table": "planilha excel dados",
  "table-2": "planilha",
  "table-cells-merge": "tabela planilha",
  "table-cells-split": "tabela planilha",
  "table-columns-split": "tabela planilha",
  "table-properties": "planilha",
  "table-rows-split": "tabela planilha",
  "tablet-smartphone": "responsivo",
  "tablets": "remédio",
  "tag": "tag preço",
  "tags": "tags",
  "tangent": "geometria",
  "target": "meta objetivo foco",
  "telescope": "espaço visão",
  "tent": "acampamento",
  "tent-tree": "acampamento",
  "terminal": "linha de comando código",
  "test-tube": "laboratório ciência",
  "test-tube-diagonal": "laboratório",
  "test-tubes": "laboratório ciência",
  "text-cursor-input": "formulário",
  "theater": "palco",
  "thermometer": "temperatura",
  "thermometer-snowflake": "temperatura",
  "thermometer-sun": "temperatura",
  "thumbs-down": "não gostei",
  "thumbs-up": "curtir gostei",
  "ticket": "bilhete cupom evento",
  "ticket-percent": "cupom",
  "timer": "tempo",
  "toggle-left": "interruptor",
  "toggle-right": "interruptor",
  "torus": "forma 3d",
  "tower-control": "aeroporto",
  "toy-brick": "lego brinquedo",
  "tractor": "agro fazenda",
  "traffic-cone": "obra construção",
  "train-front": "metrô",
  "train-front-tunnel": "metrô",
  "train-track": "ferrovia",
  "trash": "excluir apagar",
  "trash-2": "excluir",
  "tree-deciduous": "natureza",
  "tree-palm": "praia",
  "tree-pine": "árvore",
  "trees": "floresta",
  "trending-down": "tendência baixa",
  "trending-up": "tendência alta",
  "triangle": "forma",
  "triangle-alert": "atenção aviso",
  "triangle-right": "play",
  "trophy": "prêmio vitória conquista",
  "truck": "entrega frete",
  "turtle": "lento",
  "tv": "tv",
  "tv-minimal-play": "vídeo",
  "type": "fonte texto",
  "type-outline": "fonte",
  "umbrella": "proteção",
  "underline": "texto",
  "undo": "voltar",
  "university": "faculdade educação",
  "unlink": "link cortado",
  "unplug": "tomada",
  "upload": "upload subir",
  "user": "pessoa perfil aluno",
  "user-check": "pessoa",
  "user-cog": "pessoa",
  "user-minus": "pessoa",
  "user-pen": "pessoa editar perfil",
  "user-plus": "pessoa adicionar",
  "user-round": "pessoa perfil",
  "user-round-check": "pessoa",
  "user-round-cog": "pessoa",
  "user-round-minus": "pessoa",
  "user-round-pen": "pessoa",
  "user-round-plus": "pessoa",
  "user-round-search": "pessoa",
  "user-round-x": "pessoa",
  "user-search": "pessoa",
  "user-x": "pessoa",
  "users": "usuários grupo comunidade",
  "users-round": "usuários grupo",
  "utensils": "restaurante comida",
  "utensils-crossed": "restaurante",
  "utility-pole": "energia",
  "variable": "matemática código",
  "vault": "segurança",
  "vegan": "folha",
  "venetian-mask": "carnaval",
  "vibrate": "celular",
  "vibrate-off": "celular",
  "video": "câmera filmar aula",
  "video-off": "câmera",
  "view": "olho",
  "volume": "som áudio",
  "volume-1": "som áudio",
  "volume-2": "som áudio",
  "volume-x": "som áudio volume",
  "vote": "urna",
  "wallet": "dinheiro pagamento",
  "wand": "ia mágica",
  "wand-sparkles": "mágica",
  "warehouse": "estoque depósito logística",
  "waves": "água mar",
  "waypoints": "conexões",
  "webcam": "câmera",
  "webhook": "integração",
  "weight": "balança",
  "wheat": "agro",
  "wheat-off": "glúten",
  "whole-word": "texto",
  "wifi": "internet sem fio",
  "wifi-high": "internet",
  "wifi-low": "internet",
  "wifi-off": "internet",
  "wifi-zero": "internet",
  "wine": "taça bebida",
  "workflow": "automação processo",
  "wrench": "ferramenta manutenção obra",
  "x": "fechar",
  "youtube": "vídeo",
  "zap": "energia rápido",
  "zoom-in": "zoom lupa",
  "zoom-out": "zoom lupa",
};

/** O nome em português; um token desconhecido (gravado à mão antes) aparece como está. */
export function nomeDoIcone(token: string): string {
  return Object.prototype.hasOwnProperty.call(NOME_DO_ICONE, token) ? NOME_DO_ICONE[token] : token;
}
